package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.Account;

/**
 * DAO interface for table: Account.
 * @author autogenerated
 */
public interface AccountDao extends GenericDAO<Account, Serializable>  {
	// constructor only
}

