package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.AccountProductPlan;

/**
 * DAO interface for table: AccountProductPlan.
 * @author autogenerated
 */
public interface AccountProductPlanDao extends GenericDAO<AccountProductPlan, Serializable>  {
	// constructor only
}

