package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.CountryName;

/**
 * DAO interface for table: CountryName.
 * @author autogenerated
 */
public interface CountryNameDao extends GenericDAO<CountryName, Serializable>  {
	// constructor only
}

