package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.Country;

/**
 * DAO interface for table: Country.
 * @author autogenerated
 */
public interface CountryDao extends GenericDAO<Country, Serializable>  {
	// constructor only
}

