package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.Currency;

/**
 * DAO interface for table: Currency.
 * @author autogenerated
 */
public interface CurrencyDao extends GenericDAO<Currency, Serializable>  {
	// constructor only
}

