package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.CurrencyName;

/**
 * DAO interface for table: CurrencyName.
 * @author autogenerated
 */
public interface CurrencyNameDao extends GenericDAO<CurrencyName, Serializable>  {
	// constructor only
}

