package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.EmailAddress;

/**
 * DAO interface for table: EmailAddress.
 * @author autogenerated
 */
public interface EmailAddressDao extends GenericDAO<EmailAddress, Serializable>  {
	// constructor only
}

