package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.FamilyChild;

/**
 * DAO interface for table: FamilyChild.
 * @author autogenerated
 */
public interface FamilyChildDao extends GenericDAO<FamilyChild, Serializable>  {
	// constructor only
}

