package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.FamilyParent;

/**
 * DAO interface for table: FamilyParent.
 * @author autogenerated
 */
public interface FamilyParentDao extends GenericDAO<FamilyParent, Serializable>  {
	// constructor only
}

