package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.GroupMember;

/**
 * DAO interface for table: GroupMember.
 * @author autogenerated
 */
public interface GroupMemberDao extends GenericDAO<GroupMember, Serializable>  {
	// constructor only
}

