package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.LanguageName;

/**
 * DAO interface for table: LanguageName.
 * @author autogenerated
 */
public interface LanguageNameDao extends GenericDAO<LanguageName, Serializable>  {
	// constructor only
}

