package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.Language;

/**
 * DAO interface for table: Language.
 * @author autogenerated
 */
public interface LanguageDao extends GenericDAO<Language, Serializable>  {
	// constructor only
}

