package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.Offering;

/**
 * DAO interface for table: Offering.
 * @author autogenerated
 */
public interface OfferingDao extends GenericDAO<Offering, Serializable>  {
	// constructor only
}

