package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.Parent;

/**
 * DAO interface for table: Parent.
 * @author autogenerated
 */
public interface ParentDao extends GenericDAO<Parent, Serializable>  {
	// constructor only
}

