package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.PaymentFromPaypal;

/**
 * DAO interface for table: PaymentFromPaypal.
 * @author autogenerated
 */
public interface PaymentFromPaypalDao extends GenericDAO<PaymentFromPaypal, Serializable>  {
	// constructor only
}

