package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.PaymentFromCc;

/**
 * DAO interface for table: PaymentFromCc.
 * @author autogenerated
 */
public interface PaymentFromCcDao extends GenericDAO<PaymentFromCc, Serializable>  {
	// constructor only
}

