package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.Privilege;

/**
 * DAO interface for table: Privilege.
 * @author autogenerated
 */
public interface PrivilegeDao extends GenericDAO<Privilege, Serializable>  {
	// constructor only
}

