package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.PrivilegedGroup;

/**
 * DAO interface for table: PrivilegedGroup.
 * @author autogenerated
 */
public interface PrivilegedGroupDao extends GenericDAO<PrivilegedGroup, Serializable>  {
	// constructor only
}

