package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.Purchase;

/**
 * DAO interface for table: Purchase.
 * @author autogenerated
 */
public interface PurchaseDao extends GenericDAO<Purchase, Serializable>  {
	// constructor only
}

