package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.Quota;

/**
 * DAO interface for table: Quota.
 * @author autogenerated
 */
public interface QuotaDao extends GenericDAO<Quota, Serializable>  {
	// constructor only
}

