package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.RecurringChoreAssignment;

/**
 * DAO interface for table: RecurringChoreAssignment.
 * @author autogenerated
 */
public interface RecurringChoreAssignmentDao extends GenericDAO<RecurringChoreAssignment, Serializable>  {
	// constructor only
}

