package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.Refund;

/**
 * DAO interface for table: Refund.
 * @author autogenerated
 */
public interface RefundDao extends GenericDAO<Refund, Serializable>  {
	// constructor only
}

