package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.RewardPolicy;

/**
 * DAO interface for table: RewardPolicy.
 * @author autogenerated
 */
public interface RewardPolicyDao extends GenericDAO<RewardPolicy, Serializable>  {
	// constructor only
}

