package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.Reward;

/**
 * DAO interface for table: Reward.
 * @author autogenerated
 */
public interface RewardDao extends GenericDAO<Reward, Serializable>  {
	// constructor only
}

