package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.RewardLateFunction;

/**
 * DAO interface for table: RewardLateFunction.
 * @author autogenerated
 */
public interface RewardLateFunctionDao extends GenericDAO<RewardLateFunction, Serializable>  {
	// constructor only
}

