package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.Transaction;

/**
 * DAO interface for table: Transaction.
 * @author autogenerated
 */
public interface TransactionDao extends GenericDAO<Transaction, Serializable>  {
	// constructor only
}

