package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.TransactionItem;

/**
 * DAO interface for table: TransactionItem.
 * @author autogenerated
 */
public interface TransactionItemDao extends GenericDAO<TransactionItem, Serializable>  {
	// constructor only
}

