package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.TransactionItemPK;

/**
 * DAO interface for table: TransactionItemPK.
 * @author autogenerated
 */
public interface TransactionItemPKDao extends GenericDAO<TransactionItemPK, Serializable>  {
	// constructor only
}

