package com.gnoras.maple.dal.model.dao;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.GenericDAO;
import com.gnoras.maple.dal.model.User;

/**
 * DAO interface for table: User.
 * @author autogenerated
 */
public interface UserDao extends GenericDAO<User, Serializable>  {
	// constructor only
}

