package com.gnoras.maple.dal.model;

import com.felees.hbnpojogen.persistence.IPojoGenEntity;
import com.felees.hbnpojogen.persistence.validator.Mandatory;
import com.gnoras.maple.dal.model.interfaces.IAccountProductPlanAdjustment;
import java.io.Serializable;
import java.util.Collections;
import java.util.Map;
import java.util.WeakHashMap;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;
import org.hibernate.validator.Length;
import org.hibernate.validator.Valid;


/** 
 * Object mapping for hibernate-handled table: account_product_plan_adjustment.
 * @author autogenerated
 */

@Entity
@Table(name = "account_product_plan_adjustment", catalog = "maple")
public class AccountProductPlanAdjustment implements Cloneable, Serializable, IPojoGenEntity, IAccountProductPlanAdjustment {

	/** Serial Version UID. */
	private static final long serialVersionUID = -559024048L;
	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, String> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, String>());
	
	/** hashCode temporary storage. */
	private volatile String hashCode;
	

	/** Field mapping. */
	private Account account;
	/** Field mapping. */
	private Integer daysSpanned;
	/** Field mapping. */
	private String id;
	/** Field mapping. */
	private ProductPlan productPlan;
	/** Field mapping. */
	private Long startAt;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public AccountProductPlanAdjustment() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public AccountProductPlanAdjustment(String id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param account Account object;
	 * @param daysSpanned Integer object;
	 * @param id String object;
	 * @param productPlan ProductPlan object;
	 * @param startAt Long object;
	 */
	public AccountProductPlanAdjustment(Account account, Integer daysSpanned, String id, 					
			ProductPlan productPlan, Long startAt) {

		this.account = account;
		this.daysSpanned = daysSpanned;
		this.id = id;
		this.productPlan = productPlan;
		this.startAt = startAt;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return AccountProductPlanAdjustment.class;
	}
 

    /**
     * Return the value associated with the column: account.
	 * @return A Account object (this.account)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "account_id" )
	@Valid
	public Account getAccount() {
		return this.account;
		
	}
	

  
    /**  
     * Set the value related to the column: account.
	 * @param account the account value you wish to set
	 */
	public void setAccount(final Account account) {
		this.account = account;
	}

    /**
     * Return the value associated with the column: daysSpanned.
	 * @return A Integer object (this.daysSpanned)
	 */
	@Mandatory
	@Column( name = "days_spanned"  )
	public Integer getDaysSpanned() {
		return this.daysSpanned;
		
	}
	

  
    /**  
     * Set the value related to the column: daysSpanned.
	 * @param daysSpanned the daysSpanned value you wish to set
	 */
	public void setDaysSpanned(final Integer daysSpanned) {
		this.daysSpanned = daysSpanned;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
    @Id 
	@Mandatory
	@Length(max=36)
	@Column( name = "id", length = 36  )
	public String getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final String id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null ) &&
				(id != null) &&
				(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: productPlan.
	 * @return A ProductPlan object (this.productPlan)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "product_plan_id" )
	@Valid
	public ProductPlan getProductPlan() {
		return this.productPlan;
		
	}
	

  
    /**  
     * Set the value related to the column: productPlan.
	 * @param productPlan the productPlan value you wish to set
	 */
	public void setProductPlan(final ProductPlan productPlan) {
		this.productPlan = productPlan;
	}

    /**
     * Return the value associated with the column: startAt.
	 * @return A Long object (this.startAt)
	 */
	@Mandatory
	@Column( name = "start_at"  )
	public Long getStartAt() {
		return this.startAt;
		
	}
	

  
    /**  
     * Set the value related to the column: startAt.
	 * @param startAt the startAt value you wish to set
	 */
	public void setStartAt(final Long startAt) {
		this.startAt = startAt;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public AccountProductPlanAdjustment clone() throws CloneNotSupportedException {
		super.clone();  // keep hierarchy
        final AccountProductPlanAdjustment copy = new AccountProductPlanAdjustment();

		copy.setAccount(this.getAccount());
		copy.setDaysSpanned(this.getDaysSpanned());
		copy.setId(this.getId());
		copy.setProductPlan(this.getProductPlan());
		copy.setStartAt(this.getStartAt());
		return copy;
	}
	
 
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("daysSpanned: " + this.getDaysSpanned() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("startAt: " + this.getStartAt());
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final AccountProductPlanAdjustment that; 
		try {
			that = (AccountProductPlanAdjustment) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getAccount() == null) && (that.getAccount() == null)) || (getAccount() != null && getAccount().equals(that.getAccount())));
		result = result && (((getDaysSpanned() == null) && (that.getDaysSpanned() == null)) || (getDaysSpanned() != null && getDaysSpanned().equals(that.getDaysSpanned())));
		result = result && (((getProductPlan() == null) && (that.getProductPlan() == null)) || (getProductPlan() != null && getProductPlan().equals(that.getProductPlan())));
		result = result && (((getStartAt() == null) && (that.getStartAt() == null)) || (getStartAt() != null && getStartAt().equals(that.getStartAt())));
		return result;
	}
	
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					String newHashCode = null;

					if ( getId() != null ) {
						newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null ) {
							newHashCode = getId();
						} else {
						newHashCode = String.valueOf(super.hashCode());

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return this.hashCode.hashCode();
	}
	
	

	
}
