package com.gnoras.maple.dal.model;

import com.felees.hbnpojogen.persistence.IPojoGenEntity;
import com.felees.hbnpojogen.persistence.validator.Mandatory;
import com.gnoras.maple.dal.model.CountryCurrency;
import com.gnoras.maple.dal.model.CountryName;
import com.gnoras.maple.dal.model.interfaces.ICountry;
import java.io.Serializable;
import java.util.Collections;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.WeakHashMap;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;
import org.hibernate.validator.Length;
import org.hibernate.validator.Valid;


/** 
 * Object mapping for hibernate-handled table: country.
 * @author autogenerated
 */

@Entity
@Table(name = "country", catalog = "maple")
public class Country implements Cloneable, Serializable, IPojoGenEntity, ICountry {

	/** Serial Version UID. */
	private static final long serialVersionUID = -559024043L;
	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, Integer> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, Integer>());
	
	/** hashCode temporary storage. */
	private volatile Integer hashCode;
	

	/** Field mapping. */
	private Set<CountryCurrency> countryCurrencies = new HashSet<CountryCurrency>();

	/** Field mapping. */
	private Set<CountryName> countryNames = new HashSet<CountryName>();

	/** Field mapping. */
	private Integer id;
	/** Field mapping. */
	private String iso3166A2;
	/** Field mapping. */
	private String iso3166A3;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Country() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Country(Integer id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param id Integer object;
	 * @param iso3166A2 String object;
	 * @param iso3166A3 String object;
	 */
	public Country(Integer id, String iso3166A2, String iso3166A3) {

		this.id = id;
		this.iso3166A2 = iso3166A2;
		this.iso3166A3 = iso3166A3;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Country.class;
	}
 

    /**
     * Return the value associated with the column: countryCurrency.
	 * @return A Set&lt;CountryCurrency&gt; object (this.countryCurrency)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "country"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Valid
	public Set<CountryCurrency> getCountryCurrencies() {
		return this.countryCurrencies;
		
	}
	
	/**
	 * Adds a bi-directional link of type CountryCurrency to the countryCurrencies set.
	 * @param countryCurrency item to add
	 */
	public void addCountryCurrency(CountryCurrency countryCurrency) {
		countryCurrency.setCountry(this);
		this.countryCurrencies.add(countryCurrency);
	}

  
    /**  
     * Set the value related to the column: countryCurrency.
	 * @param countryCurrency the countryCurrency value you wish to set
	 */
	public void setCountryCurrencies(final Set<CountryCurrency> countryCurrency) {
		this.countryCurrencies = countryCurrency;
	}

    /**
     * Return the value associated with the column: countryName.
	 * @return A Set&lt;CountryName&gt; object (this.countryName)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "country"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Valid
	public Set<CountryName> getCountryNames() {
		return this.countryNames;
		
	}
	
	/**
	 * Adds a bi-directional link of type CountryName to the countryNames set.
	 * @param countryName item to add
	 */
	public void addCountryName(CountryName countryName) {
		countryName.setCountry(this);
		this.countryNames.add(countryName);
	}

  
    /**  
     * Set the value related to the column: countryName.
	 * @param countryName the countryName value you wish to set
	 */
	public void setCountryNames(final Set<CountryName> countryName) {
		this.countryNames = countryName;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
    @Id 
	@Mandatory
	@Column( name = "id"  )
	public Integer getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final Integer id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null || this.id == 0) &&
				(id != null) &&
				(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: iso3166A2.
	 * @return A String object (this.iso3166A2)
	 */
	@Mandatory
	@Length(max=2)
	@Column( name = "iso3166_a2", length = 2  )
	public String getIso3166A2() {
		return this.iso3166A2;
		
	}
	

  
    /**  
     * Set the value related to the column: iso3166A2.
	 * @param iso3166A2 the iso3166A2 value you wish to set
	 */
	public void setIso3166A2(final String iso3166A2) {
		this.iso3166A2 = iso3166A2;
	}

    /**
     * Return the value associated with the column: iso3166A3.
	 * @return A String object (this.iso3166A3)
	 */
	@Mandatory
	@Length(max=3)
	@Column( name = "iso3166_a3", length = 3  )
	public String getIso3166A3() {
		return this.iso3166A3;
		
	}
	

  
    /**  
     * Set the value related to the column: iso3166A3.
	 * @param iso3166A3 the iso3166A3 value you wish to set
	 */
	public void setIso3166A3(final String iso3166A3) {
		this.iso3166A3 = iso3166A3;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Country clone() throws CloneNotSupportedException {
		super.clone();  // keep hierarchy
        final Country copy = new Country();

		if (this.getCountryCurrencies() != null) {
			copy.getCountryCurrencies().addAll(this.getCountryCurrencies());
		}
		if (this.getCountryNames() != null) {
			copy.getCountryNames().addAll(this.getCountryNames());
		}
		copy.setId(this.getId());
		copy.setIso3166A2(this.getIso3166A2());
		copy.setIso3166A3(this.getIso3166A3());
		return copy;
	}
	
 
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("id: " + this.getId() + ", ");
		sb.append("iso3166A2: " + this.getIso3166A2() + ", ");
		sb.append("iso3166A3: " + this.getIso3166A3());
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final Country that; 
		try {
			that = (Country) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getIso3166A2() == null) && (that.getIso3166A2() == null)) || (getIso3166A2() != null && getIso3166A2().equals(that.getIso3166A2())));
		result = result && (((getIso3166A3() == null) && (that.getIso3166A3() == null)) || (getIso3166A3() != null && getIso3166A3().equals(that.getIso3166A3())));
		return result;
	}
	
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					Integer newHashCode = null;

					if ( getId() != null ) {
						newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null && getId() != 0) {
							newHashCode = getId();
						} else {
							newHashCode = super.hashCode();

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return this.hashCode;
	}
	
	

	
}
