package com.gnoras.maple.dal.model;

import com.felees.hbnpojogen.persistence.IPojoGenEntity;
import com.felees.hbnpojogen.persistence.validator.Mandatory;
import com.gnoras.maple.dal.model.Chore;
import com.gnoras.maple.dal.model.FamilyChild;
import com.gnoras.maple.dal.model.FamilyParent;
import com.gnoras.maple.dal.model.RewardPolicy;
import com.gnoras.maple.dal.model.RewardType;
import com.gnoras.maple.dal.model.interfaces.IFamily;
import java.io.Serializable;
import java.util.Collections;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.WeakHashMap;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;
import org.hibernate.validator.Length;
import org.hibernate.validator.Valid;


/** 
 * Object mapping for hibernate-handled table: family.
 * @author autogenerated
 */

@Entity
@Table(name = "family", catalog = "maple")
public class Family implements Cloneable, Serializable, IPojoGenEntity, IFamily {

	/** Serial Version UID. */
	private static final long serialVersionUID = -559024037L;
	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, String> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, String>());
	
	/** hashCode temporary storage. */
	private volatile String hashCode;
	

	/** Field mapping. */
	private Account account;
	/** Field mapping. */
	private Set<Chore> chores = new HashSet<Chore>();

	/** Field mapping. */
	private Long createdAt;
	/** Field mapping. */
	private Long deletedAt;
	/** Field mapping. */
	private Set<FamilyChild> familyChilds = new HashSet<FamilyChild>();

	/** Field mapping. */
	private Set<FamilyParent> familyParents = new HashSet<FamilyParent>();

	/** Field mapping. */
	private String id;
	/** Field mapping. */
	private String name;
	/** Field mapping. */
	private Set<RewardPolicy> rewardPolicies = new HashSet<RewardPolicy>();

	/** Field mapping. */
	private Set<RewardType> rewardTypes = new HashSet<RewardType>();

	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Family() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Family(String id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param account Account object;
	 * @param createdAt Long object;
	 * @param deletedAt Long object;
	 * @param id String object;
	 * @param name String object;
	 */
	public Family(Account account, Long createdAt, Long deletedAt, 					
			String id, String name) {

		this.account = account;
		this.createdAt = createdAt;
		this.deletedAt = deletedAt;
		this.id = id;
		this.name = name;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Family.class;
	}
 

    /**
     * Return the value associated with the column: account.
	 * @return A Account object (this.account)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "account_id" )
	@Valid
	public Account getAccount() {
		return this.account;
		
	}
	

  
    /**  
     * Set the value related to the column: account.
	 * @param account the account value you wish to set
	 */
	public void setAccount(final Account account) {
		this.account = account;
	}

    /**
     * Return the value associated with the column: chore.
	 * @return A Set&lt;Chore&gt; object (this.chore)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "family"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Valid
	public Set<Chore> getChores() {
		return this.chores;
		
	}
	
	/**
	 * Adds a bi-directional link of type Chore to the chores set.
	 * @param chore item to add
	 */
	public void addChore(Chore chore) {
		chore.setFamily(this);
		this.chores.add(chore);
	}

  
    /**  
     * Set the value related to the column: chore.
	 * @param chore the chore value you wish to set
	 */
	public void setChores(final Set<Chore> chore) {
		this.chores = chore;
	}

    /**
     * Return the value associated with the column: createdAt.
	 * @return A Long object (this.createdAt)
	 */
	@Mandatory
	@Column( name = "created_at"  )
	public Long getCreatedAt() {
		return this.createdAt;
		
	}
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	public void setCreatedAt(final Long createdAt) {
		this.createdAt = createdAt;
	}

    /**
     * Return the value associated with the column: deletedAt.
	 * @return A Long object (this.deletedAt)
	 */
	@Mandatory
	@Column( name = "deleted_at"  )
	public Long getDeletedAt() {
		return this.deletedAt;
		
	}
	

  
    /**  
     * Set the value related to the column: deletedAt.
	 * @param deletedAt the deletedAt value you wish to set
	 */
	public void setDeletedAt(final Long deletedAt) {
		this.deletedAt = deletedAt;
	}

    /**
     * Return the value associated with the column: familyChild.
	 * @return A Set&lt;FamilyChild&gt; object (this.familyChild)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "family"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Valid
	public Set<FamilyChild> getFamilyChilds() {
		return this.familyChilds;
		
	}
	
	/**
	 * Adds a bi-directional link of type FamilyChild to the familyChilds set.
	 * @param familyChild item to add
	 */
	public void addFamilyChild(FamilyChild familyChild) {
		familyChild.setFamily(this);
		this.familyChilds.add(familyChild);
	}

  
    /**  
     * Set the value related to the column: familyChild.
	 * @param familyChild the familyChild value you wish to set
	 */
	public void setFamilyChilds(final Set<FamilyChild> familyChild) {
		this.familyChilds = familyChild;
	}

    /**
     * Return the value associated with the column: familyParent.
	 * @return A Set&lt;FamilyParent&gt; object (this.familyParent)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "family"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Valid
	public Set<FamilyParent> getFamilyParents() {
		return this.familyParents;
		
	}
	
	/**
	 * Adds a bi-directional link of type FamilyParent to the familyParents set.
	 * @param familyParent item to add
	 */
	public void addFamilyParent(FamilyParent familyParent) {
		familyParent.setFamily(this);
		this.familyParents.add(familyParent);
	}

  
    /**  
     * Set the value related to the column: familyParent.
	 * @param familyParent the familyParent value you wish to set
	 */
	public void setFamilyParents(final Set<FamilyParent> familyParent) {
		this.familyParents = familyParent;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
    @Id 
	@Mandatory
	@Length(max=36)
	@Column( name = "id", length = 36  )
	public String getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final String id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null ) &&
				(id != null) &&
				(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	@Mandatory
	@Length(max=50)
	@Column( length = 50  )
	public String getName() {
		return this.name;
		
	}
	

  
    /**  
     * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	public void setName(final String name) {
		this.name = name;
	}

    /**
     * Return the value associated with the column: rewardPolicy.
	 * @return A Set&lt;RewardPolicy&gt; object (this.rewardPolicy)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "family"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Valid
	public Set<RewardPolicy> getRewardPolicies() {
		return this.rewardPolicies;
		
	}
	
	/**
	 * Adds a bi-directional link of type RewardPolicy to the rewardPolicies set.
	 * @param rewardPolicy item to add
	 */
	public void addRewardPolicy(RewardPolicy rewardPolicy) {
		rewardPolicy.setFamily(this);
		this.rewardPolicies.add(rewardPolicy);
	}

  
    /**  
     * Set the value related to the column: rewardPolicy.
	 * @param rewardPolicy the rewardPolicy value you wish to set
	 */
	public void setRewardPolicies(final Set<RewardPolicy> rewardPolicy) {
		this.rewardPolicies = rewardPolicy;
	}

    /**
     * Return the value associated with the column: rewardType.
	 * @return A Set&lt;RewardType&gt; object (this.rewardType)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "family"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Valid
	public Set<RewardType> getRewardTypes() {
		return this.rewardTypes;
		
	}
	
	/**
	 * Adds a bi-directional link of type RewardType to the rewardTypes set.
	 * @param rewardType item to add
	 */
	public void addRewardType(RewardType rewardType) {
		rewardType.setFamily(this);
		this.rewardTypes.add(rewardType);
	}

  
    /**  
     * Set the value related to the column: rewardType.
	 * @param rewardType the rewardType value you wish to set
	 */
	public void setRewardTypes(final Set<RewardType> rewardType) {
		this.rewardTypes = rewardType;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Family clone() throws CloneNotSupportedException {
		super.clone();  // keep hierarchy
        final Family copy = new Family();

		copy.setAccount(this.getAccount());
		if (this.getChores() != null) {
			copy.getChores().addAll(this.getChores());
		}
		copy.setCreatedAt(this.getCreatedAt());
		copy.setDeletedAt(this.getDeletedAt());
		if (this.getFamilyChilds() != null) {
			copy.getFamilyChilds().addAll(this.getFamilyChilds());
		}
		if (this.getFamilyParents() != null) {
			copy.getFamilyParents().addAll(this.getFamilyParents());
		}
		copy.setId(this.getId());
		copy.setName(this.getName());
		if (this.getRewardPolicies() != null) {
			copy.getRewardPolicies().addAll(this.getRewardPolicies());
		}
		if (this.getRewardTypes() != null) {
			copy.getRewardTypes().addAll(this.getRewardTypes());
		}
		return copy;
	}
	
 
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("createdAt: " + this.getCreatedAt() + ", ");
		sb.append("deletedAt: " + this.getDeletedAt() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("name: " + this.getName() + ", ");
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final Family that; 
		try {
			that = (Family) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getAccount() == null) && (that.getAccount() == null)) || (getAccount() != null && getAccount().equals(that.getAccount())));
		result = result && (((getCreatedAt() == null) && (that.getCreatedAt() == null)) || (getCreatedAt() != null && getCreatedAt().equals(that.getCreatedAt())));
		result = result && (((getDeletedAt() == null) && (that.getDeletedAt() == null)) || (getDeletedAt() != null && getDeletedAt().equals(that.getDeletedAt())));
		result = result && (((getName() == null) && (that.getName() == null)) || (getName() != null && getName().equals(that.getName())));
		return result;
	}
	
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					String newHashCode = null;

					if ( getId() != null ) {
						newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null ) {
							newHashCode = getId();
						} else {
						newHashCode = String.valueOf(super.hashCode());

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return this.hashCode.hashCode();
	}
	
	

	
}
