package com.gnoras.maple.dal.model;

import com.felees.hbnpojogen.persistence.IPojoGenEntity;
import com.felees.hbnpojogen.persistence.validator.Mandatory;
import com.gnoras.maple.dal.model.Purchase;
import com.gnoras.maple.dal.model.interfaces.IOffering;
import java.io.Serializable;
import java.util.Collections;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.WeakHashMap;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;
import org.hibernate.validator.Valid;


/** 
 * Object mapping for hibernate-handled table: offering.
 * @author autogenerated
 */

@Entity
@Table(name = "offering", catalog = "maple")
public class Offering implements Cloneable, Serializable, IPojoGenEntity, IOffering {

	/** Serial Version UID. */
	private static final long serialVersionUID = -559024030L;
	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, Integer> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, Integer>());
	
	/** hashCode temporary storage. */
	private volatile Integer hashCode;
	

	/** Field mapping. */
	private Currency currency;
	/** Field mapping. */
	private Long expireAt;
	/** Field mapping. */
	private Integer id;
	/** Field mapping. */
	private Double price;
	/** Field mapping. */
	private ProductPlan productPlan;
	/** Field mapping. */
	private Set<Purchase> purchases = new HashSet<Purchase>();

	/** Field mapping. */
	private Long startAt;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Offering() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Offering(Integer id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param currency Currency object;
	 * @param expireAt Long object;
	 * @param id Integer object;
	 * @param price Double object;
	 * @param productPlan ProductPlan object;
	 * @param startAt Long object;
	 */
	public Offering(Currency currency, Long expireAt, Integer id, 					
			Double price, ProductPlan productPlan, Long startAt) {

		this.currency = currency;
		this.expireAt = expireAt;
		this.id = id;
		this.price = price;
		this.productPlan = productPlan;
		this.startAt = startAt;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Offering.class;
	}
 

    /**
     * Return the value associated with the column: currency.
	 * @return A Currency object (this.currency)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "currency_id" )
	@Valid
	public Currency getCurrency() {
		return this.currency;
		
	}
	

  
    /**  
     * Set the value related to the column: currency.
	 * @param currency the currency value you wish to set
	 */
	public void setCurrency(final Currency currency) {
		this.currency = currency;
	}

    /**
     * Return the value associated with the column: expireAt.
	 * @return A Long object (this.expireAt)
	 */
	@Mandatory
	@Column( name = "expire_at"  )
	public Long getExpireAt() {
		return this.expireAt;
		
	}
	

  
    /**  
     * Set the value related to the column: expireAt.
	 * @param expireAt the expireAt value you wish to set
	 */
	public void setExpireAt(final Long expireAt) {
		this.expireAt = expireAt;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
    @Id 
	@Mandatory
	@Column( name = "id"  )
	public Integer getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final Integer id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null || this.id == 0) &&
				(id != null) &&
				(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: price.
	 * @return A Double object (this.price)
	 */
	@Mandatory
	public Double getPrice() {
		return this.price;
		
	}
	

  
    /**  
     * Set the value related to the column: price.
	 * @param price the price value you wish to set
	 */
	public void setPrice(final Double price) {
		this.price = price;
	}

    /**
     * Return the value associated with the column: productPlan.
	 * @return A ProductPlan object (this.productPlan)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "product_plan_id" )
	@Valid
	public ProductPlan getProductPlan() {
		return this.productPlan;
		
	}
	

  
    /**  
     * Set the value related to the column: productPlan.
	 * @param productPlan the productPlan value you wish to set
	 */
	public void setProductPlan(final ProductPlan productPlan) {
		this.productPlan = productPlan;
	}

    /**
     * Return the value associated with the column: purchase.
	 * @return A Set&lt;Purchase&gt; object (this.purchase)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "offering"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Valid
	public Set<Purchase> getPurchases() {
		return this.purchases;
		
	}
	
	/**
	 * Adds a bi-directional link of type Purchase to the purchases set.
	 * @param purchase item to add
	 */
	public void addPurchase(Purchase purchase) {
		purchase.setOffering(this);
		this.purchases.add(purchase);
	}

  
    /**  
     * Set the value related to the column: purchase.
	 * @param purchase the purchase value you wish to set
	 */
	public void setPurchases(final Set<Purchase> purchase) {
		this.purchases = purchase;
	}

    /**
     * Return the value associated with the column: startAt.
	 * @return A Long object (this.startAt)
	 */
	@Mandatory
	@Column( name = "start_at"  )
	public Long getStartAt() {
		return this.startAt;
		
	}
	

  
    /**  
     * Set the value related to the column: startAt.
	 * @param startAt the startAt value you wish to set
	 */
	public void setStartAt(final Long startAt) {
		this.startAt = startAt;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Offering clone() throws CloneNotSupportedException {
		super.clone();  // keep hierarchy
        final Offering copy = new Offering();

		copy.setCurrency(this.getCurrency());
		copy.setExpireAt(this.getExpireAt());
		copy.setId(this.getId());
		copy.setPrice(this.getPrice());
		copy.setProductPlan(this.getProductPlan());
		if (this.getPurchases() != null) {
			copy.getPurchases().addAll(this.getPurchases());
		}
		copy.setStartAt(this.getStartAt());
		return copy;
	}
	
 
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("expireAt: " + this.getExpireAt() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("price: " + this.getPrice() + ", ");
		sb.append("startAt: " + this.getStartAt());
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final Offering that; 
		try {
			that = (Offering) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getCurrency() == null) && (that.getCurrency() == null)) || (getCurrency() != null && getCurrency().equals(that.getCurrency())));
		result = result && (((getExpireAt() == null) && (that.getExpireAt() == null)) || (getExpireAt() != null && getExpireAt().equals(that.getExpireAt())));
		result = result && (((getPrice() == null) && (that.getPrice() == null)) || (getPrice() != null && getPrice().equals(that.getPrice())));
		result = result && (((getProductPlan() == null) && (that.getProductPlan() == null)) || (getProductPlan() != null && getProductPlan().equals(that.getProductPlan())));
		result = result && (((getStartAt() == null) && (that.getStartAt() == null)) || (getStartAt() != null && getStartAt().equals(that.getStartAt())));
		return result;
	}
	
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					Integer newHashCode = null;

					if ( getId() != null ) {
						newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null && getId() != 0) {
							newHashCode = getId();
						} else {
							newHashCode = super.hashCode();

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return this.hashCode;
	}
	
	

	
}
