package com.gnoras.maple.dal.model;

import com.felees.hbnpojogen.persistence.IPojoGenEntity;
import com.felees.hbnpojogen.persistence.validator.Mandatory;
import com.gnoras.maple.dal.model.interfaces.IPlanText;
import java.io.Serializable;
import java.util.Collections;
import java.util.Map;
import java.util.WeakHashMap;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;
import org.hibernate.validator.Length;
import org.hibernate.validator.Valid;


/** 
 * Object mapping for hibernate-handled table: plan_text.
 * @author autogenerated
 */

@Entity
@Table(name = "plan_text", catalog = "maple")
public class PlanText implements Cloneable, Serializable, IPojoGenEntity, IPlanText {

	/** Serial Version UID. */
	private static final long serialVersionUID = -559024025L;
	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, String> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, String>());
	
	/** hashCode temporary storage. */
	private volatile String hashCode;
	

	/** Field mapping. */
	private Long createdAt;
	/** Field mapping. */
	private Long deletedAt;
	/** Field mapping. */
	private String id;
	/** Field mapping. */
	private Language language;
	/** Field mapping. */
	private String planDescription;
	/** Field mapping. */
	private String planName;
	/** Field mapping. */
	private ProductPlan productPlan;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public PlanText() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public PlanText(String id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param createdAt Long object;
	 * @param deletedAt Long object;
	 * @param id String object;
	 * @param language Language object;
	 * @param planDescription String object;
	 * @param planName String object;
	 * @param productPlan ProductPlan object;
	 */
	public PlanText(Long createdAt, Long deletedAt, String id, 					
			Language language, String planDescription, String planName, 					
			ProductPlan productPlan) {

		this.createdAt = createdAt;
		this.deletedAt = deletedAt;
		this.id = id;
		this.language = language;
		this.planDescription = planDescription;
		this.planName = planName;
		this.productPlan = productPlan;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return PlanText.class;
	}
 

    /**
     * Return the value associated with the column: createdAt.
	 * @return A Long object (this.createdAt)
	 */
	@Mandatory
	@Column( name = "created_at"  )
	public Long getCreatedAt() {
		return this.createdAt;
		
	}
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	public void setCreatedAt(final Long createdAt) {
		this.createdAt = createdAt;
	}

    /**
     * Return the value associated with the column: deletedAt.
	 * @return A Long object (this.deletedAt)
	 */
	@Mandatory
	@Column( name = "deleted_at"  )
	public Long getDeletedAt() {
		return this.deletedAt;
		
	}
	

  
    /**  
     * Set the value related to the column: deletedAt.
	 * @param deletedAt the deletedAt value you wish to set
	 */
	public void setDeletedAt(final Long deletedAt) {
		this.deletedAt = deletedAt;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
    @Id 
	@Mandatory
	@Length(max=36)
	@Column( name = "id", length = 36  )
	public String getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final String id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null ) &&
				(id != null) &&
				(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: language.
	 * @return A Language object (this.language)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "language_id" )
	@Valid
	public Language getLanguage() {
		return this.language;
		
	}
	

  
    /**  
     * Set the value related to the column: language.
	 * @param language the language value you wish to set
	 */
	public void setLanguage(final Language language) {
		this.language = language;
	}

    /**
     * Return the value associated with the column: planDescription.
	 * @return A String object (this.planDescription)
	 */
	@Mandatory
	@Length(max=250)
	@Column( name = "plan_description", length = 250  )
	public String getPlanDescription() {
		return this.planDescription;
		
	}
	

  
    /**  
     * Set the value related to the column: planDescription.
	 * @param planDescription the planDescription value you wish to set
	 */
	public void setPlanDescription(final String planDescription) {
		this.planDescription = planDescription;
	}

    /**
     * Return the value associated with the column: planName.
	 * @return A String object (this.planName)
	 */
	@Mandatory
	@Length(max=50)
	@Column( name = "plan_name", length = 50  )
	public String getPlanName() {
		return this.planName;
		
	}
	

  
    /**  
     * Set the value related to the column: planName.
	 * @param planName the planName value you wish to set
	 */
	public void setPlanName(final String planName) {
		this.planName = planName;
	}

    /**
     * Return the value associated with the column: productPlan.
	 * @return A ProductPlan object (this.productPlan)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "product_plan_id" )
	@Valid
	public ProductPlan getProductPlan() {
		return this.productPlan;
		
	}
	

  
    /**  
     * Set the value related to the column: productPlan.
	 * @param productPlan the productPlan value you wish to set
	 */
	public void setProductPlan(final ProductPlan productPlan) {
		this.productPlan = productPlan;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public PlanText clone() throws CloneNotSupportedException {
		super.clone();  // keep hierarchy
        final PlanText copy = new PlanText();

		copy.setCreatedAt(this.getCreatedAt());
		copy.setDeletedAt(this.getDeletedAt());
		copy.setId(this.getId());
		copy.setLanguage(this.getLanguage());
		copy.setPlanDescription(this.getPlanDescription());
		copy.setPlanName(this.getPlanName());
		copy.setProductPlan(this.getProductPlan());
		return copy;
	}
	
 
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("createdAt: " + this.getCreatedAt() + ", ");
		sb.append("deletedAt: " + this.getDeletedAt() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("planDescription: " + this.getPlanDescription() + ", ");
		sb.append("planName: " + this.getPlanName() + ", ");
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final PlanText that; 
		try {
			that = (PlanText) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getCreatedAt() == null) && (that.getCreatedAt() == null)) || (getCreatedAt() != null && getCreatedAt().equals(that.getCreatedAt())));
		result = result && (((getDeletedAt() == null) && (that.getDeletedAt() == null)) || (getDeletedAt() != null && getDeletedAt().equals(that.getDeletedAt())));
		result = result && (((getLanguage() == null) && (that.getLanguage() == null)) || (getLanguage() != null && getLanguage().equals(that.getLanguage())));
		result = result && (((getPlanDescription() == null) && (that.getPlanDescription() == null)) || (getPlanDescription() != null && getPlanDescription().equals(that.getPlanDescription())));
		result = result && (((getPlanName() == null) && (that.getPlanName() == null)) || (getPlanName() != null && getPlanName().equals(that.getPlanName())));
		result = result && (((getProductPlan() == null) && (that.getProductPlan() == null)) || (getProductPlan() != null && getProductPlan().equals(that.getProductPlan())));
		return result;
	}
	
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					String newHashCode = null;

					if ( getId() != null ) {
						newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null ) {
							newHashCode = getId();
						} else {
						newHashCode = String.valueOf(super.hashCode());

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return this.hashCode.hashCode();
	}
	
	

	
}
