package com.gnoras.maple.dal.model;

import com.felees.hbnpojogen.persistence.IPojoGenEntity;
import com.felees.hbnpojogen.persistence.validator.Mandatory;
import com.gnoras.maple.dal.model.Refund;
import com.gnoras.maple.dal.model.TransactionItem;
import com.gnoras.maple.dal.model.interfaces.IPurchase;
import java.io.Serializable;
import java.util.Collections;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.WeakHashMap;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;
import org.hibernate.validator.Length;
import org.hibernate.validator.Valid;


/** 
 * Object mapping for hibernate-handled table: purchase.
 * @author autogenerated
 */

@Entity
@Table(name = "purchase", catalog = "maple")
public class Purchase implements Cloneable, Serializable, IPojoGenEntity, IPurchase {

	/** Serial Version UID. */
	private static final long serialVersionUID = -559024021L;
	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, String> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, String>());
	
	/** hashCode temporary storage. */
	private volatile String hashCode;
	

	/** Field mapping. */
	private Account account;
	/** Field mapping. */
	private String id;
	/** Field mapping. */
	private Offering offering;
	/** Field mapping. */
	private Set<Refund> refunds = new HashSet<Refund>();

	/** Field mapping. */
	private Set<TransactionItem> transactionItems = new HashSet<TransactionItem>();

	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Purchase() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Purchase(String id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param account Account object;
	 * @param id String object;
	 * @param offering Offering object;
	 */
	public Purchase(Account account, String id, Offering offering) {

		this.account = account;
		this.id = id;
		this.offering = offering;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Purchase.class;
	}
 

    /**
     * Return the value associated with the column: account.
	 * @return A Account object (this.account)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "account_id" )
	@Valid
	public Account getAccount() {
		return this.account;
		
	}
	

  
    /**  
     * Set the value related to the column: account.
	 * @param account the account value you wish to set
	 */
	public void setAccount(final Account account) {
		this.account = account;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
    @Id 
	@Mandatory
	@Length(max=36)
	@Column( name = "id", length = 36  )
	public String getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final String id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null ) &&
				(id != null) &&
				(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: offering.
	 * @return A Offering object (this.offering)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "offering_id" )
	@Valid
	public Offering getOffering() {
		return this.offering;
		
	}
	

  
    /**  
     * Set the value related to the column: offering.
	 * @param offering the offering value you wish to set
	 */
	public void setOffering(final Offering offering) {
		this.offering = offering;
	}

    /**
     * Return the value associated with the column: refund.
	 * @return A Set&lt;Refund&gt; object (this.refund)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "purchase"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Valid
	public Set<Refund> getRefunds() {
		return this.refunds;
		
	}
	
	/**
	 * Adds a bi-directional link of type Refund to the refunds set.
	 * @param refund item to add
	 */
	public void addRefund(Refund refund) {
		refund.setPurchase(this);
		this.refunds.add(refund);
	}

  
    /**  
     * Set the value related to the column: refund.
	 * @param refund the refund value you wish to set
	 */
	public void setRefunds(final Set<Refund> refund) {
		this.refunds = refund;
	}

    /**
     * Return the value associated with the column: transactionItem.
	 * @return A Set&lt;TransactionItem&gt; object (this.transactionItem)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "id.purchase"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Valid
	public Set<TransactionItem> getTransactionItems() {
		return this.transactionItems;
		
	}
	
	/**
	 * Adds a bi-directional link of type TransactionItem to the transactionItems set.
	 * @param transactionItem item to add
	 */
	public void addTransactionItem(TransactionItem transactionItem) {
		transactionItem.getId().setPurchase(this);
		this.transactionItems.add(transactionItem);
	}

  
    /**  
     * Set the value related to the column: transactionItem.
	 * @param transactionItem the transactionItem value you wish to set
	 */
	public void setTransactionItems(final Set<TransactionItem> transactionItem) {
		this.transactionItems = transactionItem;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Purchase clone() throws CloneNotSupportedException {
		super.clone();  // keep hierarchy
        final Purchase copy = new Purchase();

		copy.setAccount(this.getAccount());
		copy.setId(this.getId());
		copy.setOffering(this.getOffering());
		if (this.getRefunds() != null) {
			copy.getRefunds().addAll(this.getRefunds());
		}
		if (this.getTransactionItems() != null) {
			copy.getTransactionItems().addAll(this.getTransactionItems());
		}
		return copy;
	}
	
 
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("id: " + this.getId() + ", ");
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final Purchase that; 
		try {
			that = (Purchase) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getAccount() == null) && (that.getAccount() == null)) || (getAccount() != null && getAccount().equals(that.getAccount())));
		result = result && (((getOffering() == null) && (that.getOffering() == null)) || (getOffering() != null && getOffering().equals(that.getOffering())));
		return result;
	}
	
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					String newHashCode = null;

					if ( getId() != null ) {
						newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null ) {
							newHashCode = getId();
						} else {
						newHashCode = String.valueOf(super.hashCode());

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return this.hashCode.hashCode();
	}
	
	

	
}
