package com.gnoras.maple.dal.model;

import com.felees.hbnpojogen.persistence.IPojoGenEntity;
import com.felees.hbnpojogen.persistence.validator.Mandatory;
import com.gnoras.maple.dal.model.interfaces.IQuota;
import java.io.Serializable;
import java.util.Collections;
import java.util.Map;
import java.util.WeakHashMap;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;
import org.hibernate.validator.Length;


/** 
 * Object mapping for hibernate-handled table: quota.
 * @author autogenerated
 */

@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@Table(name = "quota", catalog = "maple")
public class Quota implements Cloneable, Serializable, IPojoGenEntity, IQuota {

	/** Serial Version UID. */
	private static final long serialVersionUID = -559024020L;
	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, String> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, String>());
	
	/** hashCode temporary storage. */
	private volatile String hashCode;
	

	/** Field mapping. */
	private Integer choreAlertsUsedThisWk;
	/** Field mapping. */
	private String id;
	/** Field mapping. */
	private Integer maxChildren;
	/** Field mapping. */
	private Integer maxChoreAlertsThisWeek;
	/** Field mapping. */
	private Integer reportLevel;
	/** Field mapping. */
	private Integer rewardLevel;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Quota() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Quota(String id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param choreAlertsUsedThisWk Integer object;
	 * @param id String object;
	 * @param maxChildren Integer object;
	 * @param maxChoreAlertsThisWeek Integer object;
	 * @param reportLevel Integer object;
	 * @param rewardLevel Integer object;
	 */
	public Quota(Integer choreAlertsUsedThisWk, String id, Integer maxChildren, 					
			Integer maxChoreAlertsThisWeek, Integer reportLevel, Integer rewardLevel) {

		this.choreAlertsUsedThisWk = choreAlertsUsedThisWk;
		this.id = id;
		this.maxChildren = maxChildren;
		this.maxChoreAlertsThisWeek = maxChoreAlertsThisWeek;
		this.reportLevel = reportLevel;
		this.rewardLevel = rewardLevel;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Quota.class;
	}
 

    /**
     * Return the value associated with the column: choreAlertsUsedThisWk.
	 * @return A Integer object (this.choreAlertsUsedThisWk)
	 */
	@Mandatory
	@Column( name = "chore_alerts_used_this_wk"  )
	public Integer getChoreAlertsUsedThisWk() {
		return this.choreAlertsUsedThisWk;
		
	}
	

  
    /**  
     * Set the value related to the column: choreAlertsUsedThisWk.
	 * @param choreAlertsUsedThisWk the choreAlertsUsedThisWk value you wish to set
	 */
	public void setChoreAlertsUsedThisWk(final Integer choreAlertsUsedThisWk) {
		this.choreAlertsUsedThisWk = choreAlertsUsedThisWk;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
    @Id 
	@Mandatory
	@Length(max=36)
	@Column( name = "id", length = 36  )
	public String getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final String id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null ) &&
				(id != null) &&
				(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: maxChildren.
	 * @return A Integer object (this.maxChildren)
	 */
	@Mandatory
	@Column( name = "max_children"  )
	public Integer getMaxChildren() {
		return this.maxChildren;
		
	}
	

  
    /**  
     * Set the value related to the column: maxChildren.
	 * @param maxChildren the maxChildren value you wish to set
	 */
	public void setMaxChildren(final Integer maxChildren) {
		this.maxChildren = maxChildren;
	}

    /**
     * Return the value associated with the column: maxChoreAlertsThisWeek.
	 * @return A Integer object (this.maxChoreAlertsThisWeek)
	 */
	@Mandatory
	@Column( name = "max_chore_alerts_this_week"  )
	public Integer getMaxChoreAlertsThisWeek() {
		return this.maxChoreAlertsThisWeek;
		
	}
	

  
    /**  
     * Set the value related to the column: maxChoreAlertsThisWeek.
	 * @param maxChoreAlertsThisWeek the maxChoreAlertsThisWeek value you wish to set
	 */
	public void setMaxChoreAlertsThisWeek(final Integer maxChoreAlertsThisWeek) {
		this.maxChoreAlertsThisWeek = maxChoreAlertsThisWeek;
	}

    /**
     * Return the value associated with the column: reportLevel.
	 * @return A Integer object (this.reportLevel)
	 */
	@Mandatory
	@Column( name = "report_level"  )
	public Integer getReportLevel() {
		return this.reportLevel;
		
	}
	

  
    /**  
     * Set the value related to the column: reportLevel.
	 * @param reportLevel the reportLevel value you wish to set
	 */
	public void setReportLevel(final Integer reportLevel) {
		this.reportLevel = reportLevel;
	}

    /**
     * Return the value associated with the column: rewardLevel.
	 * @return A Integer object (this.rewardLevel)
	 */
	@Mandatory
	@Column( name = "reward_level"  )
	public Integer getRewardLevel() {
		return this.rewardLevel;
		
	}
	

  
    /**  
     * Set the value related to the column: rewardLevel.
	 * @param rewardLevel the rewardLevel value you wish to set
	 */
	public void setRewardLevel(final Integer rewardLevel) {
		this.rewardLevel = rewardLevel;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Quota clone() throws CloneNotSupportedException {
		super.clone();  // keep hierarchy
        final Quota copy = new Quota();

		copy.setChoreAlertsUsedThisWk(this.getChoreAlertsUsedThisWk());
		copy.setId(this.getId());
		copy.setMaxChildren(this.getMaxChildren());
		copy.setMaxChoreAlertsThisWeek(this.getMaxChoreAlertsThisWeek());
		copy.setReportLevel(this.getReportLevel());
		copy.setRewardLevel(this.getRewardLevel());
		return copy;
	}
	
 
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("choreAlertsUsedThisWk: " + this.getChoreAlertsUsedThisWk() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("maxChildren: " + this.getMaxChildren() + ", ");
		sb.append("maxChoreAlertsThisWeek: " + this.getMaxChoreAlertsThisWeek() + ", ");
		sb.append("reportLevel: " + this.getReportLevel() + ", ");
		sb.append("rewardLevel: " + this.getRewardLevel());
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final Quota that; 
		try {
			that = (Quota) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getChoreAlertsUsedThisWk() == null) && (that.getChoreAlertsUsedThisWk() == null)) || (getChoreAlertsUsedThisWk() != null && getChoreAlertsUsedThisWk().equals(that.getChoreAlertsUsedThisWk())));
		result = result && (((getMaxChildren() == null) && (that.getMaxChildren() == null)) || (getMaxChildren() != null && getMaxChildren().equals(that.getMaxChildren())));
		result = result && (((getMaxChoreAlertsThisWeek() == null) && (that.getMaxChoreAlertsThisWeek() == null)) || (getMaxChoreAlertsThisWeek() != null && getMaxChoreAlertsThisWeek().equals(that.getMaxChoreAlertsThisWeek())));
		result = result && (((getReportLevel() == null) && (that.getReportLevel() == null)) || (getReportLevel() != null && getReportLevel().equals(that.getReportLevel())));
		result = result && (((getRewardLevel() == null) && (that.getRewardLevel() == null)) || (getRewardLevel() != null && getRewardLevel().equals(that.getRewardLevel())));
		return result;
	}
	
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					String newHashCode = null;

					if ( getId() != null ) {
						newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null ) {
							newHashCode = getId();
						} else {
						newHashCode = String.valueOf(super.hashCode());

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return this.hashCode.hashCode();
	}
	
	

	
}
