package com.gnoras.maple.dal.model;

import com.felees.hbnpojogen.persistence.IPojoGenEntity;
import com.felees.hbnpojogen.persistence.validator.Mandatory;
import com.gnoras.maple.dal.model.TransactionItem;
import com.gnoras.maple.dal.model.interfaces.IRefund;
import java.io.Serializable;
import java.util.Collections;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.WeakHashMap;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;
import org.hibernate.validator.Length;
import org.hibernate.validator.Valid;


/** 
 * Object mapping for hibernate-handled table: refund.
 * @author autogenerated
 */

@Entity
@Table(name = "refund", catalog = "maple")
public class Refund implements Cloneable, Serializable, IPojoGenEntity, IRefund {

	/** Serial Version UID. */
	private static final long serialVersionUID = -559024018L;
	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, String> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, String>());
	
	/** hashCode temporary storage. */
	private volatile String hashCode;
	

	/** Field mapping. */
	private Integer daysRefunded;
	/** Field mapping. */
	private String id;
	/** Field mapping. */
	private Purchase purchase;
	/** Field mapping. */
	private Set<TransactionItem> transactionItems = new HashSet<TransactionItem>();

	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Refund() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Refund(String id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param daysRefunded Integer object;
	 * @param id String object;
	 * @param purchase Purchase object;
	 */
	public Refund(Integer daysRefunded, String id, Purchase purchase) {

		this.daysRefunded = daysRefunded;
		this.id = id;
		this.purchase = purchase;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Refund.class;
	}
 

    /**
     * Return the value associated with the column: daysRefunded.
	 * @return A Integer object (this.daysRefunded)
	 */
	@Mandatory
	@Column( name = "days_refunded"  )
	public Integer getDaysRefunded() {
		return this.daysRefunded;
		
	}
	

  
    /**  
     * Set the value related to the column: daysRefunded.
	 * @param daysRefunded the daysRefunded value you wish to set
	 */
	public void setDaysRefunded(final Integer daysRefunded) {
		this.daysRefunded = daysRefunded;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
    @Id 
	@Mandatory
	@Length(max=36)
	@Column( name = "id", length = 36  )
	public String getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final String id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null ) &&
				(id != null) &&
				(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: purchase.
	 * @return A Purchase object (this.purchase)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "purchase_id" )
	@Valid
	public Purchase getPurchase() {
		return this.purchase;
		
	}
	

  
    /**  
     * Set the value related to the column: purchase.
	 * @param purchase the purchase value you wish to set
	 */
	public void setPurchase(final Purchase purchase) {
		this.purchase = purchase;
	}

    /**
     * Return the value associated with the column: transactionItem.
	 * @return A Set&lt;TransactionItem&gt; object (this.transactionItem)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "id.refund"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Valid
	public Set<TransactionItem> getTransactionItems() {
		return this.transactionItems;
		
	}
	
	/**
	 * Adds a bi-directional link of type TransactionItem to the transactionItems set.
	 * @param transactionItem item to add
	 */
	public void addTransactionItem(TransactionItem transactionItem) {
		transactionItem.getId().setRefund(this);
		this.transactionItems.add(transactionItem);
	}

  
    /**  
     * Set the value related to the column: transactionItem.
	 * @param transactionItem the transactionItem value you wish to set
	 */
	public void setTransactionItems(final Set<TransactionItem> transactionItem) {
		this.transactionItems = transactionItem;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Refund clone() throws CloneNotSupportedException {
		super.clone();  // keep hierarchy
        final Refund copy = new Refund();

		copy.setDaysRefunded(this.getDaysRefunded());
		copy.setId(this.getId());
		copy.setPurchase(this.getPurchase());
		if (this.getTransactionItems() != null) {
			copy.getTransactionItems().addAll(this.getTransactionItems());
		}
		return copy;
	}
	
 
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("daysRefunded: " + this.getDaysRefunded() + ", ");
		sb.append("id: " + this.getId() + ", ");
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final Refund that; 
		try {
			that = (Refund) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getDaysRefunded() == null) && (that.getDaysRefunded() == null)) || (getDaysRefunded() != null && getDaysRefunded().equals(that.getDaysRefunded())));
		result = result && (((getPurchase() == null) && (that.getPurchase() == null)) || (getPurchase() != null && getPurchase().equals(that.getPurchase())));
		return result;
	}
	
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					String newHashCode = null;

					if ( getId() != null ) {
						newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null ) {
							newHashCode = getId();
						} else {
						newHashCode = String.valueOf(super.hashCode());

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return this.hashCode.hashCode();
	}
	
	

	
}
