package com.gnoras.maple.core.subsystems;

import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;

import com.gnoras.maple.core.interfaces.ILanguageSubsystem;
import com.gnoras.maple.dal.factories.HibernateMapleDaoFactory;
import com.gnoras.maple.dal.model.Language;
import com.gnoras.maple.dal.model.interfaces.ILanguage;

public class LanguageSubsystem implements ILanguageSubsystem {

	@Override
	public List<ILanguage> getLanguages() {
		List<Language> languages = HibernateMapleDaoFactory.getLanguageDao()
				.findAll();
		// TODO move the List<interface> code into the autogenerated model's
		// code
		List<ILanguage> ilanguages = new ArrayList<ILanguage>(languages.size());
		ListIterator<Language> iterator = languages.listIterator();
		while (iterator.hasNext()) {
			Language language = iterator.next();
			ilanguages.add(language);
		}
		return ilanguages;
	}

}