package com.gnoras.maple.dal.factories;

import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.BeanNameAware;

import com.gnoras.maple.dal.model.dao.*;

/** 
 * DAO factory implementation.
 * @author autogenerated
 */
@Component
public class HibernateMapleDaoFactory implements ApplicationContextAware, BeanNameAware {
	/** Placeholder for an instance. */
	private static HibernateMapleDaoFactory instance;
	/** Internal state. */
	private static ApplicationContext context = null;
	/** Bean Name. */
	private static String beanName;

	/** Return an instance of this class.
	 * @return an instance of this class
	 */
	public static synchronized HibernateMapleDaoFactory getInstance() {
		if (instance == null) {
			instance = (HibernateMapleDaoFactory) context.getBean(beanName);
		}
		return instance;
	}

	/**
	 * Sets a Spring Application Context object.
  	 * @param ctxt ApplicationContext to set
	 * @throws BeansException on spring error
	 */
	@Autowired
	public void setApplicationContext(ApplicationContext ctxt)
			throws BeansException 
	{
		context = ctxt;
	}

	/**
	* 
	* {@inheritDoc}
	* 
	* @see org.springframework.beans.factory.BeanNameAware#setBeanName(java.lang.String)
	*/
	public void setBeanName(String name) {
		beanName = name;
	}

	/**
	 * Return the requested bean from the context, throwing a RuntimeException on error.
	 *
	 * @param beanName to return
	 * @return the bean requested.
	 */
	public static Object getBean(String beanName) {
		Object result = context.getBean(beanName);
		if (result == null) { 
			throw new IllegalStateException(String.format("Could not find bean '%s'. Did you set the right component scanning?", beanName));
		} 
		
		return result;
	}

	
	/**
	 * Returns a AccountDao instance.
	 * 
	 * @return a AccountDao instance
	 */
	public static AccountDao getAccountDao() {
		return (AccountDao) getBean("accountDaoImpl"); 
	}
	/**
	 * Returns a AccountProductPlanDao instance.
	 * 
	 * @return a AccountProductPlanDao instance
	 */
	public static AccountProductPlanDao getAccountProductPlanDao() {
		return (AccountProductPlanDao) getBean("accountProductPlanDaoImpl"); 
	}
	/**
	 * Returns a AccountProductPlanAdjustmentDao instance.
	 * 
	 * @return a AccountProductPlanAdjustmentDao instance
	 */
	public static AccountProductPlanAdjustmentDao getAccountProductPlanAdjustmentDao() {
		return (AccountProductPlanAdjustmentDao) getBean("accountProductPlanAdjustmentDaoImpl"); 
	}
	/**
	 * Returns a AccountStateDao instance.
	 * 
	 * @return a AccountStateDao instance
	 */
	public static AccountStateDao getAccountStateDao() {
		return (AccountStateDao) getBean("accountStateDaoImpl"); 
	}
	/**
	 * Returns a ChildDao instance.
	 * 
	 * @return a ChildDao instance
	 */
	public static ChildDao getChildDao() {
		return (ChildDao) getBean("childDaoImpl"); 
	}
	/**
	 * Returns a ChoreDao instance.
	 * 
	 * @return a ChoreDao instance
	 */
	public static ChoreDao getChoreDao() {
		return (ChoreDao) getBean("choreDaoImpl"); 
	}
	/**
	 * Returns a ChoreAssignmentDao instance.
	 * 
	 * @return a ChoreAssignmentDao instance
	 */
	public static ChoreAssignmentDao getChoreAssignmentDao() {
		return (ChoreAssignmentDao) getBean("choreAssignmentDaoImpl"); 
	}
	/**
	 * Returns a CountryDao instance.
	 * 
	 * @return a CountryDao instance
	 */
	public static CountryDao getCountryDao() {
		return (CountryDao) getBean("countryDaoImpl"); 
	}
	/**
	 * Returns a CountryCurrencyDao instance.
	 * 
	 * @return a CountryCurrencyDao instance
	 */
	public static CountryCurrencyDao getCountryCurrencyDao() {
		return (CountryCurrencyDao) getBean("countryCurrencyDaoImpl"); 
	}
	/**
	 * Returns a CountryNameDao instance.
	 * 
	 * @return a CountryNameDao instance
	 */
	public static CountryNameDao getCountryNameDao() {
		return (CountryNameDao) getBean("countryNameDaoImpl"); 
	}
	/**
	 * Returns a CurrencyDao instance.
	 * 
	 * @return a CurrencyDao instance
	 */
	public static CurrencyDao getCurrencyDao() {
		return (CurrencyDao) getBean("currencyDaoImpl"); 
	}
	/**
	 * Returns a CurrencyNameDao instance.
	 * 
	 * @return a CurrencyNameDao instance
	 */
	public static CurrencyNameDao getCurrencyNameDao() {
		return (CurrencyNameDao) getBean("currencyNameDaoImpl"); 
	}
	/**
	 * Returns a EmailAddressDao instance.
	 * 
	 * @return a EmailAddressDao instance
	 */
	public static EmailAddressDao getEmailAddressDao() {
		return (EmailAddressDao) getBean("emailAddressDaoImpl"); 
	}
	/**
	 * Returns a FamilyDao instance.
	 * 
	 * @return a FamilyDao instance
	 */
	public static FamilyDao getFamilyDao() {
		return (FamilyDao) getBean("familyDaoImpl"); 
	}
	/**
	 * Returns a FamilyChildDao instance.
	 * 
	 * @return a FamilyChildDao instance
	 */
	public static FamilyChildDao getFamilyChildDao() {
		return (FamilyChildDao) getBean("familyChildDaoImpl"); 
	}
	/**
	 * Returns a FamilyParentDao instance.
	 * 
	 * @return a FamilyParentDao instance
	 */
	public static FamilyParentDao getFamilyParentDao() {
		return (FamilyParentDao) getBean("familyParentDaoImpl"); 
	}
	/**
	 * Returns a GroupDao instance.
	 * 
	 * @return a GroupDao instance
	 */
	public static GroupDao getGroupDao() {
		return (GroupDao) getBean("groupDaoImpl"); 
	}
	/**
	 * Returns a GroupMemberDao instance.
	 * 
	 * @return a GroupMemberDao instance
	 */
	public static GroupMemberDao getGroupMemberDao() {
		return (GroupMemberDao) getBean("groupMemberDaoImpl"); 
	}
	/**
	 * Returns a LanguageDao instance.
	 * 
	 * @return a LanguageDao instance
	 */
	public static LanguageDao getLanguageDao() {
		return (LanguageDao) getBean("languageDaoImpl"); 
	}
	/**
	 * Returns a LanguageNameDao instance.
	 * 
	 * @return a LanguageNameDao instance
	 */
	public static LanguageNameDao getLanguageNameDao() {
		return (LanguageNameDao) getBean("languageNameDaoImpl"); 
	}
	/**
	 * Returns a OfferingDao instance.
	 * 
	 * @return a OfferingDao instance
	 */
	public static OfferingDao getOfferingDao() {
		return (OfferingDao) getBean("offeringDaoImpl"); 
	}
	/**
	 * Returns a ParentDao instance.
	 * 
	 * @return a ParentDao instance
	 */
	public static ParentDao getParentDao() {
		return (ParentDao) getBean("parentDaoImpl"); 
	}
	/**
	 * Returns a PaymentFromCcDao instance.
	 * 
	 * @return a PaymentFromCcDao instance
	 */
	public static PaymentFromCcDao getPaymentFromCcDao() {
		return (PaymentFromCcDao) getBean("paymentFromCcDaoImpl"); 
	}
	/**
	 * Returns a PaymentFromPaypalDao instance.
	 * 
	 * @return a PaymentFromPaypalDao instance
	 */
	public static PaymentFromPaypalDao getPaymentFromPaypalDao() {
		return (PaymentFromPaypalDao) getBean("paymentFromPaypalDaoImpl"); 
	}
	/**
	 * Returns a PaymentTypeDao instance.
	 * 
	 * @return a PaymentTypeDao instance
	 */
	public static PaymentTypeDao getPaymentTypeDao() {
		return (PaymentTypeDao) getBean("paymentTypeDaoImpl"); 
	}
	/**
	 * Returns a PlanTextDao instance.
	 * 
	 * @return a PlanTextDao instance
	 */
	public static PlanTextDao getPlanTextDao() {
		return (PlanTextDao) getBean("planTextDaoImpl"); 
	}
	/**
	 * Returns a PrivilegeDao instance.
	 * 
	 * @return a PrivilegeDao instance
	 */
	public static PrivilegeDao getPrivilegeDao() {
		return (PrivilegeDao) getBean("privilegeDaoImpl"); 
	}
	/**
	 * Returns a PrivilegedGroupDao instance.
	 * 
	 * @return a PrivilegedGroupDao instance
	 */
	public static PrivilegedGroupDao getPrivilegedGroupDao() {
		return (PrivilegedGroupDao) getBean("privilegedGroupDaoImpl"); 
	}
	/**
	 * Returns a ProductPlanDao instance.
	 * 
	 * @return a ProductPlanDao instance
	 */
	public static ProductPlanDao getProductPlanDao() {
		return (ProductPlanDao) getBean("productPlanDaoImpl"); 
	}
	/**
	 * Returns a PurchaseDao instance.
	 * 
	 * @return a PurchaseDao instance
	 */
	public static PurchaseDao getPurchaseDao() {
		return (PurchaseDao) getBean("purchaseDaoImpl"); 
	}
	/**
	 * Returns a QuotaDao instance.
	 * 
	 * @return a QuotaDao instance
	 */
	public static QuotaDao getQuotaDao() {
		return (QuotaDao) getBean("quotaDaoImpl"); 
	}
	/**
	 * Returns a RecurringChoreAssignmentDao instance.
	 * 
	 * @return a RecurringChoreAssignmentDao instance
	 */
	public static RecurringChoreAssignmentDao getRecurringChoreAssignmentDao() {
		return (RecurringChoreAssignmentDao) getBean("recurringChoreAssignmentDaoImpl"); 
	}
	/**
	 * Returns a RefundDao instance.
	 * 
	 * @return a RefundDao instance
	 */
	public static RefundDao getRefundDao() {
		return (RefundDao) getBean("refundDaoImpl"); 
	}
	/**
	 * Returns a RewardDao instance.
	 * 
	 * @return a RewardDao instance
	 */
	public static RewardDao getRewardDao() {
		return (RewardDao) getBean("rewardDaoImpl"); 
	}
	/**
	 * Returns a RewardEarlyFunctionDao instance.
	 * 
	 * @return a RewardEarlyFunctionDao instance
	 */
	public static RewardEarlyFunctionDao getRewardEarlyFunctionDao() {
		return (RewardEarlyFunctionDao) getBean("rewardEarlyFunctionDaoImpl"); 
	}
	/**
	 * Returns a RewardLateFunctionDao instance.
	 * 
	 * @return a RewardLateFunctionDao instance
	 */
	public static RewardLateFunctionDao getRewardLateFunctionDao() {
		return (RewardLateFunctionDao) getBean("rewardLateFunctionDaoImpl"); 
	}
	/**
	 * Returns a RewardPolicyDao instance.
	 * 
	 * @return a RewardPolicyDao instance
	 */
	public static RewardPolicyDao getRewardPolicyDao() {
		return (RewardPolicyDao) getBean("rewardPolicyDaoImpl"); 
	}
	/**
	 * Returns a RewardTypeDao instance.
	 * 
	 * @return a RewardTypeDao instance
	 */
	public static RewardTypeDao getRewardTypeDao() {
		return (RewardTypeDao) getBean("rewardTypeDaoImpl"); 
	}
	/**
	 * Returns a TransactionDao instance.
	 * 
	 * @return a TransactionDao instance
	 */
	public static TransactionDao getTransactionDao() {
		return (TransactionDao) getBean("transactionDaoImpl"); 
	}
	/**
	 * Returns a TransactionItemDao instance.
	 * 
	 * @return a TransactionItemDao instance
	 */
	public static TransactionItemDao getTransactionItemDao() {
		return (TransactionItemDao) getBean("transactionItemDaoImpl"); 
	}
	/**
	 * Returns a UserDao instance.
	 * 
	 * @return a UserDao instance
	 */
	public static UserDao getUserDao() {
		return (UserDao) getBean("userDaoImpl"); 
	}

}
