package com.gnoras.maple.dal.model.interfaces;
import com.gnoras.maple.dal.model.Account;
import java.util.Set;


/** 
 * Object interface mapping for hibernate-handled table: account_state.
 * @author autogenerated
 */

public interface IAccountState {



    /**
     * Return the value associated with the column: account.
	 * @return A Set&lt;Account&gt; object (this.account)
	 */
	Set<Account> getAccounts();
	
	/**
	 * Adds a bi-directional link of type Account to the accounts set.
	 * @param account item to add
	 */
	void addAccount(Account account);

  
    /**  
     * Set the value related to the column: account.
	 * @param account the account value you wish to set
	 */
	void setAccounts(final Set<Account> account);

    /**
     * Return the value associated with the column: description.
	 * @return A String object (this.description)
	 */
	String getDescription();
	

  
    /**  
     * Set the value related to the column: description.
	 * @param description the description value you wish to set
	 */
	void setDescription(final String description);

    /**
     * Return the value associated with the column: enumName.
	 * @return A String object (this.enumName)
	 */
	String getEnumName();
	

  
    /**  
     * Set the value related to the column: enumName.
	 * @param enumName the enumName value you wish to set
	 */
	void setEnumName(final String enumName);

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
	Integer getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Integer id);

    /**
     * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	String getName();
	

  
    /**  
     * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	void setName(final String name);

	// end of interface
}