package com.gnoras.maple.dal.model.interfaces;
import com.gnoras.maple.dal.model.AccountProductPlan;
import com.gnoras.maple.dal.model.AccountProductPlanAdjustment;
import com.gnoras.maple.dal.model.AccountState;
import com.gnoras.maple.dal.model.Family;
import com.gnoras.maple.dal.model.Purchase;
import java.util.Set;


/** 
 * Object interface mapping for hibernate-handled table: account.
 * @author autogenerated
 */

public interface IAccount extends IQuota {



    /**
     * Return the value associated with the column: accountProductPlan.
	 * @return A Set&lt;AccountProductPlan&gt; object (this.accountProductPlan)
	 */
	Set<AccountProductPlan> getAccountProductPlans();
	
	/**
	 * Adds a bi-directional link of type AccountProductPlan to the accountProductPlans set.
	 * @param accountProductPlan item to add
	 */
	void addAccountProductPlan(AccountProductPlan accountProductPlan);

  
    /**  
     * Set the value related to the column: accountProductPlan.
	 * @param accountProductPlan the accountProductPlan value you wish to set
	 */
	void setAccountProductPlans(final Set<AccountProductPlan> accountProductPlan);

    /**
     * Return the value associated with the column: accountProductPlanAdjustment.
	 * @return A Set&lt;AccountProductPlanAdjustment&gt; object (this.accountProductPlanAdjustment)
	 */
	Set<AccountProductPlanAdjustment> getAccountProductPlanAdjustments();
	
	/**
	 * Adds a bi-directional link of type AccountProductPlanAdjustment to the accountProductPlanAdjustments set.
	 * @param accountProductPlanAdjustment item to add
	 */
	void addAccountProductPlanAdjustment(AccountProductPlanAdjustment accountProductPlanAdjustment);

  
    /**  
     * Set the value related to the column: accountProductPlanAdjustment.
	 * @param accountProductPlanAdjustment the accountProductPlanAdjustment value you wish to set
	 */
	void setAccountProductPlanAdjustments(final Set<AccountProductPlanAdjustment> accountProductPlanAdjustment);

    /**
     * Return the value associated with the column: createdAt.
	 * @return A Long object (this.createdAt)
	 */
	Long getCreatedAt();
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	void setCreatedAt(final Long createdAt);

    /**
     * Return the value associated with the column: deletedAt.
	 * @return A Long object (this.deletedAt)
	 */
	Long getDeletedAt();
	

  
    /**  
     * Set the value related to the column: deletedAt.
	 * @param deletedAt the deletedAt value you wish to set
	 */
	void setDeletedAt(final Long deletedAt);

    /**
     * Return the value associated with the column: family.
	 * @return A Set&lt;Family&gt; object (this.family)
	 */
	Set<Family> getFamilies();
	
	/**
	 * Adds a bi-directional link of type Family to the families set.
	 * @param family item to add
	 */
	void addFamily(Family family);

  
    /**  
     * Set the value related to the column: family.
	 * @param family the family value you wish to set
	 */
	void setFamilies(final Set<Family> family);

    /**
     * Return the value associated with the column: purchase.
	 * @return A Set&lt;Purchase&gt; object (this.purchase)
	 */
	Set<Purchase> getPurchases();
	
	/**
	 * Adds a bi-directional link of type Purchase to the purchases set.
	 * @param purchase item to add
	 */
	void addPurchase(Purchase purchase);

  
    /**  
     * Set the value related to the column: purchase.
	 * @param purchase the purchase value you wish to set
	 */
	void setPurchases(final Set<Purchase> purchase);

    /**
     * Return the value associated with the column: quotaId.
	 * @return A String object (this.quotaId)
	 */
	String getQuotaId();
	

  
    /**  
     * Set the value related to the column: quotaId.
	 * @param quotaId the quotaId value you wish to set
	 */
	void setQuotaId(final String quotaId);

    /**
     * Return the value associated with the column: state.
	 * @return A AccountState object (this.state)
	 */
	AccountState getState();
	

  
    /**  
     * Set the value related to the column: state.
	 * @param state the state value you wish to set
	 */
	void setState(final AccountState state);

	// end of interface
}