package com.gnoras.maple.dal.model.interfaces;
import com.gnoras.maple.dal.model.ChoreAssignment;
import com.gnoras.maple.dal.model.Family;
import com.gnoras.maple.dal.model.RecurringChoreAssignment;
import com.gnoras.maple.dal.model.Reward;
import com.gnoras.maple.dal.model.RewardPolicy;
import java.util.Set;


/** 
 * Object interface mapping for hibernate-handled table: chore.
 * @author autogenerated
 */

public interface IChore {



    /**
     * Return the value associated with the column: choreAssignment.
	 * @return A Set&lt;ChoreAssignment&gt; object (this.choreAssignment)
	 */
	Set<ChoreAssignment> getChoreAssignments();
	
	/**
	 * Adds a bi-directional link of type ChoreAssignment to the choreAssignments set.
	 * @param choreAssignment item to add
	 */
	void addChoreAssignment(ChoreAssignment choreAssignment);

  
    /**  
     * Set the value related to the column: choreAssignment.
	 * @param choreAssignment the choreAssignment value you wish to set
	 */
	void setChoreAssignments(final Set<ChoreAssignment> choreAssignment);

    /**
     * Return the value associated with the column: createdDt.
	 * @return A Long object (this.createdDt)
	 */
	Long getCreatedDt();
	

  
    /**  
     * Set the value related to the column: createdDt.
	 * @param createdDt the createdDt value you wish to set
	 */
	void setCreatedDt(final Long createdDt);

    /**
     * Return the value associated with the column: defReward.
	 * @return A Reward object (this.defReward)
	 */
	Reward getDefReward();
	

  
    /**  
     * Set the value related to the column: defReward.
	 * @param defReward the defReward value you wish to set
	 */
	void setDefReward(final Reward defReward);

    /**
     * Return the value associated with the column: defRewardPolicy.
	 * @return A RewardPolicy object (this.defRewardPolicy)
	 */
	RewardPolicy getDefRewardPolicy();
	

  
    /**  
     * Set the value related to the column: defRewardPolicy.
	 * @param defRewardPolicy the defRewardPolicy value you wish to set
	 */
	void setDefRewardPolicy(final RewardPolicy defRewardPolicy);

    /**
     * Return the value associated with the column: deletedDt.
	 * @return A Long object (this.deletedDt)
	 */
	Long getDeletedDt();
	

  
    /**  
     * Set the value related to the column: deletedDt.
	 * @param deletedDt the deletedDt value you wish to set
	 */
	void setDeletedDt(final Long deletedDt);

    /**
     * Return the value associated with the column: description.
	 * @return A String object (this.description)
	 */
	String getDescription();
	

  
    /**  
     * Set the value related to the column: description.
	 * @param description the description value you wish to set
	 */
	void setDescription(final String description);

    /**
     * Return the value associated with the column: family.
	 * @return A Family object (this.family)
	 */
	Family getFamily();
	

  
    /**  
     * Set the value related to the column: family.
	 * @param family the family value you wish to set
	 */
	void setFamily(final Family family);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	String getName();
	

  
    /**  
     * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	void setName(final String name);

    /**
     * Return the value associated with the column: recurringChoreAssignment.
	 * @return A Set&lt;RecurringChoreAssignment&gt; object (this.recurringChoreAssignment)
	 */
	Set<RecurringChoreAssignment> getRecurringChoreAssignments();
	
	/**
	 * Adds a bi-directional link of type RecurringChoreAssignment to the recurringChoreAssignments set.
	 * @param recurringChoreAssignment item to add
	 */
	void addRecurringChoreAssignment(RecurringChoreAssignment recurringChoreAssignment);

  
    /**  
     * Set the value related to the column: recurringChoreAssignment.
	 * @param recurringChoreAssignment the recurringChoreAssignment value you wish to set
	 */
	void setRecurringChoreAssignments(final Set<RecurringChoreAssignment> recurringChoreAssignment);

    /**
     * Return the value associated with the column: retired.
	 * @return A Byte object (this.retired)
	 */
	Byte getRetired();
	

  
    /**  
     * Set the value related to the column: retired.
	 * @param retired the retired value you wish to set
	 */
	void setRetired(final Byte retired);

	// end of interface
}