package com.gnoras.maple.dal.model.interfaces;
import com.gnoras.maple.dal.model.Child;
import com.gnoras.maple.dal.model.Chore;
import com.gnoras.maple.dal.model.Parent;
import com.gnoras.maple.dal.model.RewardPolicy;


/** 
 * Object interface mapping for hibernate-handled table: chore_assignment.
 * @author autogenerated
 */

public interface IChoreAssignment {



    /**
     * Return the value associated with the column: child.
	 * @return A Child object (this.child)
	 */
	Child getChild();
	

  
    /**  
     * Set the value related to the column: child.
	 * @param child the child value you wish to set
	 */
	void setChild(final Child child);

    /**
     * Return the value associated with the column: chore.
	 * @return A Chore object (this.chore)
	 */
	Chore getChore();
	

  
    /**  
     * Set the value related to the column: chore.
	 * @param chore the chore value you wish to set
	 */
	void setChore(final Chore chore);

    /**
     * Return the value associated with the column: completedAt.
	 * @return A Long object (this.completedAt)
	 */
	Long getCompletedAt();
	

  
    /**  
     * Set the value related to the column: completedAt.
	 * @param completedAt the completedAt value you wish to set
	 */
	void setCompletedAt(final Long completedAt);

    /**
     * Return the value associated with the column: dueAt.
	 * @return A Long object (this.dueAt)
	 */
	Long getDueAt();
	

  
    /**  
     * Set the value related to the column: dueAt.
	 * @param dueAt the dueAt value you wish to set
	 */
	void setDueAt(final Long dueAt);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: parent.
	 * @return A Parent object (this.parent)
	 */
	Parent getParent();
	

  
    /**  
     * Set the value related to the column: parent.
	 * @param parent the parent value you wish to set
	 */
	void setParent(final Parent parent);

    /**
     * Return the value associated with the column: rewardGranted.
	 * @return A Double object (this.rewardGranted)
	 */
	Double getRewardGranted();
	

  
    /**  
     * Set the value related to the column: rewardGranted.
	 * @param rewardGranted the rewardGranted value you wish to set
	 */
	void setRewardGranted(final Double rewardGranted);

    /**
     * Return the value associated with the column: rewardId.
	 * @return A String object (this.rewardId)
	 */
	String getRewardId();
	

  
    /**  
     * Set the value related to the column: rewardId.
	 * @param rewardId the rewardId value you wish to set
	 */
	void setRewardId(final String rewardId);

    /**
     * Return the value associated with the column: rewardPolicy.
	 * @return A RewardPolicy object (this.rewardPolicy)
	 */
	RewardPolicy getRewardPolicy();
	

  
    /**  
     * Set the value related to the column: rewardPolicy.
	 * @param rewardPolicy the rewardPolicy value you wish to set
	 */
	void setRewardPolicy(final RewardPolicy rewardPolicy);

	// end of interface
}