package com.gnoras.maple.dal.model.interfaces;
import com.gnoras.maple.dal.model.CountryCurrency;
import com.gnoras.maple.dal.model.CountryName;
import java.util.Set;


/** 
 * Object interface mapping for hibernate-handled table: country.
 * @author autogenerated
 */

public interface ICountry {



    /**
     * Return the value associated with the column: countryCurrency.
	 * @return A Set&lt;CountryCurrency&gt; object (this.countryCurrency)
	 */
	Set<CountryCurrency> getCountryCurrencies();
	
	/**
	 * Adds a bi-directional link of type CountryCurrency to the countryCurrencies set.
	 * @param countryCurrency item to add
	 */
	void addCountryCurrency(CountryCurrency countryCurrency);

  
    /**  
     * Set the value related to the column: countryCurrency.
	 * @param countryCurrency the countryCurrency value you wish to set
	 */
	void setCountryCurrencies(final Set<CountryCurrency> countryCurrency);

    /**
     * Return the value associated with the column: countryName.
	 * @return A Set&lt;CountryName&gt; object (this.countryName)
	 */
	Set<CountryName> getCountryNames();
	
	/**
	 * Adds a bi-directional link of type CountryName to the countryNames set.
	 * @param countryName item to add
	 */
	void addCountryName(CountryName countryName);

  
    /**  
     * Set the value related to the column: countryName.
	 * @param countryName the countryName value you wish to set
	 */
	void setCountryNames(final Set<CountryName> countryName);

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
	Integer getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Integer id);

    /**
     * Return the value associated with the column: iso3166A2.
	 * @return A String object (this.iso3166A2)
	 */
	String getIso3166A2();
	

  
    /**  
     * Set the value related to the column: iso3166A2.
	 * @param iso3166A2 the iso3166A2 value you wish to set
	 */
	void setIso3166A2(final String iso3166A2);

    /**
     * Return the value associated with the column: iso3166A3.
	 * @return A String object (this.iso3166A3)
	 */
	String getIso3166A3();
	

  
    /**  
     * Set the value related to the column: iso3166A3.
	 * @param iso3166A3 the iso3166A3 value you wish to set
	 */
	void setIso3166A3(final String iso3166A3);

	// end of interface
}