package com.gnoras.maple.dal.model.interfaces;
import com.gnoras.maple.dal.model.CountryCurrency;
import com.gnoras.maple.dal.model.CurrencyName;
import com.gnoras.maple.dal.model.Offering;
import java.util.Set;


/** 
 * Object interface mapping for hibernate-handled table: currency.
 * @author autogenerated
 */

public interface ICurrency {



    /**
     * Return the value associated with the column: countryCurrency.
	 * @return A Set&lt;CountryCurrency&gt; object (this.countryCurrency)
	 */
	Set<CountryCurrency> getCountryCurrencies();
	
	/**
	 * Adds a bi-directional link of type CountryCurrency to the countryCurrencies set.
	 * @param countryCurrency item to add
	 */
	void addCountryCurrency(CountryCurrency countryCurrency);

  
    /**  
     * Set the value related to the column: countryCurrency.
	 * @param countryCurrency the countryCurrency value you wish to set
	 */
	void setCountryCurrencies(final Set<CountryCurrency> countryCurrency);

    /**
     * Return the value associated with the column: currencyName.
	 * @return A Set&lt;CurrencyName&gt; object (this.currencyName)
	 */
	Set<CurrencyName> getCurrencyNames();
	
	/**
	 * Adds a bi-directional link of type CurrencyName to the currencyNames set.
	 * @param currencyName item to add
	 */
	void addCurrencyName(CurrencyName currencyName);

  
    /**  
     * Set the value related to the column: currencyName.
	 * @param currencyName the currencyName value you wish to set
	 */
	void setCurrencyNames(final Set<CurrencyName> currencyName);

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
	Integer getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Integer id);

    /**
     * Return the value associated with the column: iso4217.
	 * @return A String object (this.iso4217)
	 */
	String getIso4217();
	

  
    /**  
     * Set the value related to the column: iso4217.
	 * @param iso4217 the iso4217 value you wish to set
	 */
	void setIso4217(final String iso4217);

    /**
     * Return the value associated with the column: offering.
	 * @return A Set&lt;Offering&gt; object (this.offering)
	 */
	Set<Offering> getOfferings();
	
	/**
	 * Adds a bi-directional link of type Offering to the offerings set.
	 * @param offering item to add
	 */
	void addOffering(Offering offering);

  
    /**  
     * Set the value related to the column: offering.
	 * @param offering the offering value you wish to set
	 */
	void setOfferings(final Set<Offering> offering);

    /**
     * Return the value associated with the column: symbol.
	 * @return A String object (this.symbol)
	 */
	String getSymbol();
	

  
    /**  
     * Set the value related to the column: symbol.
	 * @param symbol the symbol value you wish to set
	 */
	void setSymbol(final String symbol);

	// end of interface
}