package com.gnoras.maple.dal.model.interfaces;
import com.gnoras.maple.dal.model.Child;
import com.gnoras.maple.dal.model.Family;


/** 
 * Object interface mapping for hibernate-handled table: family_child.
 * @author autogenerated
 */

public interface IFamilyChild {



    /**
     * Return the value associated with the column: child.
	 * @return A Child object (this.child)
	 */
	Child getChild();
	

  
    /**  
     * Set the value related to the column: child.
	 * @param child the child value you wish to set
	 */
	void setChild(final Child child);

    /**
     * Return the value associated with the column: family.
	 * @return A Family object (this.family)
	 */
	Family getFamily();
	

  
    /**  
     * Set the value related to the column: family.
	 * @param family the family value you wish to set
	 */
	void setFamily(final Family family);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

	// end of interface
}