package com.gnoras.maple.dal.model.interfaces;
import com.gnoras.maple.dal.model.GroupMember;
import com.gnoras.maple.dal.model.PrivilegedGroup;
import java.util.Set;


/** 
 * Object interface mapping for hibernate-handled table: group.
 * @author autogenerated
 */

public interface IGroup {



    /**
     * Return the value associated with the column: createdAt.
	 * @return A Long object (this.createdAt)
	 */
	Long getCreatedAt();
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	void setCreatedAt(final Long createdAt);

    /**
     * Return the value associated with the column: deletedAt.
	 * @return A Long object (this.deletedAt)
	 */
	Long getDeletedAt();
	

  
    /**  
     * Set the value related to the column: deletedAt.
	 * @param deletedAt the deletedAt value you wish to set
	 */
	void setDeletedAt(final Long deletedAt);

    /**
     * Return the value associated with the column: description.
	 * @return A String object (this.description)
	 */
	String getDescription();
	

  
    /**  
     * Set the value related to the column: description.
	 * @param description the description value you wish to set
	 */
	void setDescription(final String description);

    /**
     * Return the value associated with the column: groupMember.
	 * @return A Set&lt;GroupMember&gt; object (this.groupMember)
	 */
	Set<GroupMember> getGroupMembers();
	
	/**
	 * Adds a bi-directional link of type GroupMember to the groupMembers set.
	 * @param groupMember item to add
	 */
	void addGroupMember(GroupMember groupMember);

  
    /**  
     * Set the value related to the column: groupMember.
	 * @param groupMember the groupMember value you wish to set
	 */
	void setGroupMembers(final Set<GroupMember> groupMember);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	String getName();
	

  
    /**  
     * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	void setName(final String name);

    /**
     * Return the value associated with the column: privilegedGroup.
	 * @return A Set&lt;PrivilegedGroup&gt; object (this.privilegedGroup)
	 */
	Set<PrivilegedGroup> getPrivilegedGroups();
	
	/**
	 * Adds a bi-directional link of type PrivilegedGroup to the privilegedGroups set.
	 * @param privilegedGroup item to add
	 */
	void addPrivilegedGroup(PrivilegedGroup privilegedGroup);

  
    /**  
     * Set the value related to the column: privilegedGroup.
	 * @param privilegedGroup the privilegedGroup value you wish to set
	 */
	void setPrivilegedGroups(final Set<PrivilegedGroup> privilegedGroup);

	// end of interface
}