package com.gnoras.maple.dal.model.interfaces;
import com.gnoras.maple.dal.model.Currency;
import com.gnoras.maple.dal.model.ProductPlan;
import com.gnoras.maple.dal.model.Purchase;
import java.util.Set;


/** 
 * Object interface mapping for hibernate-handled table: offering.
 * @author autogenerated
 */

public interface IOffering {



    /**
     * Return the value associated with the column: currency.
	 * @return A Currency object (this.currency)
	 */
	Currency getCurrency();
	

  
    /**  
     * Set the value related to the column: currency.
	 * @param currency the currency value you wish to set
	 */
	void setCurrency(final Currency currency);

    /**
     * Return the value associated with the column: expireAt.
	 * @return A Long object (this.expireAt)
	 */
	Long getExpireAt();
	

  
    /**  
     * Set the value related to the column: expireAt.
	 * @param expireAt the expireAt value you wish to set
	 */
	void setExpireAt(final Long expireAt);

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
	Integer getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Integer id);

    /**
     * Return the value associated with the column: price.
	 * @return A Double object (this.price)
	 */
	Double getPrice();
	

  
    /**  
     * Set the value related to the column: price.
	 * @param price the price value you wish to set
	 */
	void setPrice(final Double price);

    /**
     * Return the value associated with the column: productPlan.
	 * @return A ProductPlan object (this.productPlan)
	 */
	ProductPlan getProductPlan();
	

  
    /**  
     * Set the value related to the column: productPlan.
	 * @param productPlan the productPlan value you wish to set
	 */
	void setProductPlan(final ProductPlan productPlan);

    /**
     * Return the value associated with the column: purchase.
	 * @return A Set&lt;Purchase&gt; object (this.purchase)
	 */
	Set<Purchase> getPurchases();
	
	/**
	 * Adds a bi-directional link of type Purchase to the purchases set.
	 * @param purchase item to add
	 */
	void addPurchase(Purchase purchase);

  
    /**  
     * Set the value related to the column: purchase.
	 * @param purchase the purchase value you wish to set
	 */
	void setPurchases(final Set<Purchase> purchase);

    /**
     * Return the value associated with the column: startAt.
	 * @return A Long object (this.startAt)
	 */
	Long getStartAt();
	

  
    /**  
     * Set the value related to the column: startAt.
	 * @param startAt the startAt value you wish to set
	 */
	void setStartAt(final Long startAt);

	// end of interface
}