package com.gnoras.maple.dal.model.interfaces;
import com.gnoras.maple.dal.model.Transaction;
import java.util.Set;


/** 
 * Object interface mapping for hibernate-handled table: payment_type.
 * @author autogenerated
 */

public interface IPaymentType {



    /**
     * Return the value associated with the column: enumName.
	 * @return A String object (this.enumName)
	 */
	String getEnumName();
	

  
    /**  
     * Set the value related to the column: enumName.
	 * @param enumName the enumName value you wish to set
	 */
	void setEnumName(final String enumName);

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
	Integer getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Integer id);

    /**
     * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	String getName();
	

  
    /**  
     * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	void setName(final String name);

    /**
     * Return the value associated with the column: transaction.
	 * @return A Set&lt;Transaction&gt; object (this.transaction)
	 */
	Set<Transaction> getTransactions();
	
	/**
	 * Adds a bi-directional link of type Transaction to the transactions set.
	 * @param transaction item to add
	 */
	void addTransaction(Transaction transaction);

  
    /**  
     * Set the value related to the column: transaction.
	 * @param transaction the transaction value you wish to set
	 */
	void setTransactions(final Set<Transaction> transaction);

	// end of interface
}