package com.gnoras.maple.dal.model.interfaces;
import com.gnoras.maple.dal.model.Language;
import com.gnoras.maple.dal.model.ProductPlan;


/** 
 * Object interface mapping for hibernate-handled table: plan_text.
 * @author autogenerated
 */

public interface IPlanText {



    /**
     * Return the value associated with the column: createdAt.
	 * @return A Long object (this.createdAt)
	 */
	Long getCreatedAt();
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	void setCreatedAt(final Long createdAt);

    /**
     * Return the value associated with the column: deletedAt.
	 * @return A Long object (this.deletedAt)
	 */
	Long getDeletedAt();
	

  
    /**  
     * Set the value related to the column: deletedAt.
	 * @param deletedAt the deletedAt value you wish to set
	 */
	void setDeletedAt(final Long deletedAt);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: language.
	 * @return A Language object (this.language)
	 */
	Language getLanguage();
	

  
    /**  
     * Set the value related to the column: language.
	 * @param language the language value you wish to set
	 */
	void setLanguage(final Language language);

    /**
     * Return the value associated with the column: planDescription.
	 * @return A String object (this.planDescription)
	 */
	String getPlanDescription();
	

  
    /**  
     * Set the value related to the column: planDescription.
	 * @param planDescription the planDescription value you wish to set
	 */
	void setPlanDescription(final String planDescription);

    /**
     * Return the value associated with the column: planName.
	 * @return A String object (this.planName)
	 */
	String getPlanName();
	

  
    /**  
     * Set the value related to the column: planName.
	 * @param planName the planName value you wish to set
	 */
	void setPlanName(final String planName);

    /**
     * Return the value associated with the column: productPlan.
	 * @return A ProductPlan object (this.productPlan)
	 */
	ProductPlan getProductPlan();
	

  
    /**  
     * Set the value related to the column: productPlan.
	 * @param productPlan the productPlan value you wish to set
	 */
	void setProductPlan(final ProductPlan productPlan);

	// end of interface
}