package com.gnoras.maple.dal.model.interfaces;
import com.gnoras.maple.dal.model.PrivilegedGroup;
import java.util.Set;


/** 
 * Object interface mapping for hibernate-handled table: privilege.
 * @author autogenerated
 */

public interface IPrivilege {



    /**
     * Return the value associated with the column: description.
	 * @return A String object (this.description)
	 */
	String getDescription();
	

  
    /**  
     * Set the value related to the column: description.
	 * @param description the description value you wish to set
	 */
	void setDescription(final String description);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	String getName();
	

  
    /**  
     * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	void setName(final String name);

    /**
     * Return the value associated with the column: privilegedGroup.
	 * @return A Set&lt;PrivilegedGroup&gt; object (this.privilegedGroup)
	 */
	Set<PrivilegedGroup> getPrivilegedGroups();
	
	/**
	 * Adds a bi-directional link of type PrivilegedGroup to the privilegedGroups set.
	 * @param privilegedGroup item to add
	 */
	void addPrivilegedGroup(PrivilegedGroup privilegedGroup);

  
    /**  
     * Set the value related to the column: privilegedGroup.
	 * @param privilegedGroup the privilegedGroup value you wish to set
	 */
	void setPrivilegedGroups(final Set<PrivilegedGroup> privilegedGroup);

	// end of interface
}