package com.gnoras.maple.dal.model.interfaces;
import com.gnoras.maple.dal.model.Chore;
import com.gnoras.maple.dal.model.ChoreAssignment;
import com.gnoras.maple.dal.model.Family;
import com.gnoras.maple.dal.model.RewardEarlyFunction;
import com.gnoras.maple.dal.model.RewardLateFunction;
import java.util.Set;


/** 
 * Object interface mapping for hibernate-handled table: reward_policy.
 * @author autogenerated
 */

public interface IRewardPolicy {



    /**
     * Return the value associated with the column: chore.
	 * @return A Set&lt;Chore&gt; object (this.chore)
	 */
	Set<Chore> getChores();
	
	/**
	 * Adds a bi-directional link of type Chore to the chores set.
	 * @param chore item to add
	 */
	void addChore(Chore chore);

  
    /**  
     * Set the value related to the column: chore.
	 * @param chore the chore value you wish to set
	 */
	void setChores(final Set<Chore> chore);

    /**
     * Return the value associated with the column: choreAssignment.
	 * @return A Set&lt;ChoreAssignment&gt; object (this.choreAssignment)
	 */
	Set<ChoreAssignment> getChoreAssignments();
	
	/**
	 * Adds a bi-directional link of type ChoreAssignment to the choreAssignments set.
	 * @param choreAssignment item to add
	 */
	void addChoreAssignment(ChoreAssignment choreAssignment);

  
    /**  
     * Set the value related to the column: choreAssignment.
	 * @param choreAssignment the choreAssignment value you wish to set
	 */
	void setChoreAssignments(final Set<ChoreAssignment> choreAssignment);

    /**
     * Return the value associated with the column: earlyArg1.
	 * @return A Double object (this.earlyArg1)
	 */
	Double getEarlyArg1();
	

  
    /**  
     * Set the value related to the column: earlyArg1.
	 * @param earlyArg1 the earlyArg1 value you wish to set
	 */
	void setEarlyArg1(final Double earlyArg1);

    /**
     * Return the value associated with the column: earlyArg2.
	 * @return A Double object (this.earlyArg2)
	 */
	Double getEarlyArg2();
	

  
    /**  
     * Set the value related to the column: earlyArg2.
	 * @param earlyArg2 the earlyArg2 value you wish to set
	 */
	void setEarlyArg2(final Double earlyArg2);

    /**
     * Return the value associated with the column: family.
	 * @return A Family object (this.family)
	 */
	Family getFamily();
	

  
    /**  
     * Set the value related to the column: family.
	 * @param family the family value you wish to set
	 */
	void setFamily(final Family family);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: lateArg1.
	 * @return A Double object (this.lateArg1)
	 */
	Double getLateArg1();
	

  
    /**  
     * Set the value related to the column: lateArg1.
	 * @param lateArg1 the lateArg1 value you wish to set
	 */
	void setLateArg1(final Double lateArg1);

    /**
     * Return the value associated with the column: lateArg2.
	 * @return A Double object (this.lateArg2)
	 */
	Double getLateArg2();
	

  
    /**  
     * Set the value related to the column: lateArg2.
	 * @param lateArg2 the lateArg2 value you wish to set
	 */
	void setLateArg2(final Double lateArg2);

    /**
     * Return the value associated with the column: rewardEarlyFunction.
	 * @return A RewardEarlyFunction object (this.rewardEarlyFunction)
	 */
	RewardEarlyFunction getRewardEarlyFunction();
	

  
    /**  
     * Set the value related to the column: rewardEarlyFunction.
	 * @param rewardEarlyFunction the rewardEarlyFunction value you wish to set
	 */
	void setRewardEarlyFunction(final RewardEarlyFunction rewardEarlyFunction);

    /**
     * Return the value associated with the column: rewardLateFunction.
	 * @return A RewardLateFunction object (this.rewardLateFunction)
	 */
	RewardLateFunction getRewardLateFunction();
	

  
    /**  
     * Set the value related to the column: rewardLateFunction.
	 * @param rewardLateFunction the rewardLateFunction value you wish to set
	 */
	void setRewardLateFunction(final RewardLateFunction rewardLateFunction);

	// end of interface
}