package com.gnoras.maple.dal.model.interfaces;
import com.gnoras.maple.dal.model.Family;
import com.gnoras.maple.dal.model.Reward;
import java.util.Set;


/** 
 * Object interface mapping for hibernate-handled table: reward_type.
 * @author autogenerated
 */

public interface IRewardType {



    /**
     * Return the value associated with the column: createdAt.
	 * @return A Long object (this.createdAt)
	 */
	Long getCreatedAt();
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	void setCreatedAt(final Long createdAt);

    /**
     * Return the value associated with the column: deletedAt.
	 * @return A Long object (this.deletedAt)
	 */
	Long getDeletedAt();
	

  
    /**  
     * Set the value related to the column: deletedAt.
	 * @param deletedAt the deletedAt value you wish to set
	 */
	void setDeletedAt(final Long deletedAt);

    /**
     * Return the value associated with the column: description.
	 * @return A String object (this.description)
	 */
	String getDescription();
	

  
    /**  
     * Set the value related to the column: description.
	 * @param description the description value you wish to set
	 */
	void setDescription(final String description);

    /**
     * Return the value associated with the column: family.
	 * @return A Family object (this.family)
	 */
	Family getFamily();
	

  
    /**  
     * Set the value related to the column: family.
	 * @param family the family value you wish to set
	 */
	void setFamily(final Family family);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	String getName();
	

  
    /**  
     * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	void setName(final String name);

    /**
     * Return the value associated with the column: reward.
	 * @return A Set&lt;Reward&gt; object (this.reward)
	 */
	Set<Reward> getRewards();
	
	/**
	 * Adds a bi-directional link of type Reward to the rewards set.
	 * @param reward item to add
	 */
	void addReward(Reward reward);

  
    /**  
     * Set the value related to the column: reward.
	 * @param reward the reward value you wish to set
	 */
	void setRewards(final Set<Reward> reward);

	// end of interface
}