package com.gnoras.maple.dal.model.interfaces;
import com.gnoras.maple.dal.model.Purchase;
import com.gnoras.maple.dal.model.Refund;
import com.gnoras.maple.dal.model.Transaction;


/** 
 * Object interface mapping for hibernate-handled table: transaction_item.
 * @author autogenerated
 */

public interface ITransactionItemPK {



    /**
     * Return the value associated with the column: purchase.
	 * @return A Purchase object (this.purchase)
	 */
	Purchase getPurchase();
	

  
    /**  
     * Set the value related to the column: purchase.
	 * @param purchase the purchase value you wish to set
	 */
	void setPurchase(final Purchase purchase);

    /**
     * Return the value associated with the column: refund.
	 * @return A Refund object (this.refund)
	 */
	Refund getRefund();
	

  
    /**  
     * Set the value related to the column: refund.
	 * @param refund the refund value you wish to set
	 */
	void setRefund(final Refund refund);

    /**
     * Return the value associated with the column: transaction.
	 * @return A Transaction object (this.transaction)
	 */
	Transaction getTransaction();
	

  
    /**  
     * Set the value related to the column: transaction.
	 * @param transaction the transaction value you wish to set
	 */
	void setTransaction(final Transaction transaction);

	// end of interface
}