package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.AccountProductPlan;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.AccountProductPlanDao;

/**
 * DAO for table: AccountProductPlan.
 * @author autogenerated
 */
@Repository
public class AccountProductPlanDaoImpl extends GenericHibernateDaoImpl<AccountProductPlan, Serializable> implements AccountProductPlanDao {
	
	/** Constructor method. */
		public AccountProductPlanDaoImpl() {
			super(AccountProductPlan.class);
		}
	}

