package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.Child;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.ChildDao;

/**
 * DAO for table: Child.
 * @author autogenerated
 */
@Repository
public class ChildDaoImpl extends GenericHibernateDaoImpl<Child, Serializable> implements ChildDao {
	
	/** Constructor method. */
		public ChildDaoImpl() {
			super(Child.class);
		}
	}

