package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.CountryCurrency;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.CountryCurrencyDao;

/**
 * DAO for table: CountryCurrency.
 * @author autogenerated
 */
@Repository
public class CountryCurrencyDaoImpl extends GenericHibernateDaoImpl<CountryCurrency, Serializable> implements CountryCurrencyDao {
	
	/** Constructor method. */
		public CountryCurrencyDaoImpl() {
			super(CountryCurrency.class);
		}
	}

