package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.CurrencyName;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.CurrencyNameDao;

/**
 * DAO for table: CurrencyName.
 * @author autogenerated
 */
@Repository
public class CurrencyNameDaoImpl extends GenericHibernateDaoImpl<CurrencyName, Serializable> implements CurrencyNameDao {
	
	/** Constructor method. */
		public CurrencyNameDaoImpl() {
			super(CurrencyName.class);
		}
	}

