package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.Currency;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.CurrencyDao;

/**
 * DAO for table: Currency.
 * @author autogenerated
 */
@Repository
public class CurrencyDaoImpl extends GenericHibernateDaoImpl<Currency, Serializable> implements CurrencyDao {
	
	/** Constructor method. */
		public CurrencyDaoImpl() {
			super(Currency.class);
		}
	}

