package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.EmailAddress;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.EmailAddressDao;

/**
 * DAO for table: EmailAddress.
 * @author autogenerated
 */
@Repository
public class EmailAddressDaoImpl extends GenericHibernateDaoImpl<EmailAddress, Serializable> implements EmailAddressDao {
	
	/** Constructor method. */
		public EmailAddressDaoImpl() {
			super(EmailAddress.class);
		}
	}

