package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.FamilyChild;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.FamilyChildDao;

/**
 * DAO for table: FamilyChild.
 * @author autogenerated
 */
@Repository
public class FamilyChildDaoImpl extends GenericHibernateDaoImpl<FamilyChild, Serializable> implements FamilyChildDao {
	
	/** Constructor method. */
		public FamilyChildDaoImpl() {
			super(FamilyChild.class);
		}
	}

