package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.Group;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.GroupDao;

/**
 * DAO for table: Group.
 * @author autogenerated
 */
@Repository
public class GroupDaoImpl extends GenericHibernateDaoImpl<Group, Serializable> implements GroupDao {
	
	/** Constructor method. */
		public GroupDaoImpl() {
			super(Group.class);
		}
	}

