package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.LanguageName;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.LanguageNameDao;

/**
 * DAO for table: LanguageName.
 * @author autogenerated
 */
@Repository
public class LanguageNameDaoImpl extends GenericHibernateDaoImpl<LanguageName, Serializable> implements LanguageNameDao {
	
	/** Constructor method. */
		public LanguageNameDaoImpl() {
			super(LanguageName.class);
		}
	}

