package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.Offering;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.OfferingDao;

/**
 * DAO for table: Offering.
 * @author autogenerated
 */
@Repository
public class OfferingDaoImpl extends GenericHibernateDaoImpl<Offering, Serializable> implements OfferingDao {
	
	/** Constructor method. */
		public OfferingDaoImpl() {
			super(Offering.class);
		}
	}

