package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.Parent;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.ParentDao;

/**
 * DAO for table: Parent.
 * @author autogenerated
 */
@Repository
public class ParentDaoImpl extends GenericHibernateDaoImpl<Parent, Serializable> implements ParentDao {
	
	/** Constructor method. */
		public ParentDaoImpl() {
			super(Parent.class);
		}
	}

