package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.PaymentFromCc;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.PaymentFromCcDao;

/**
 * DAO for table: PaymentFromCc.
 * @author autogenerated
 */
@Repository
public class PaymentFromCcDaoImpl extends GenericHibernateDaoImpl<PaymentFromCc, Serializable> implements PaymentFromCcDao {
	
	/** Constructor method. */
		public PaymentFromCcDaoImpl() {
			super(PaymentFromCc.class);
		}
	}

