package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.Privilege;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.PrivilegeDao;

/**
 * DAO for table: Privilege.
 * @author autogenerated
 */
@Repository
public class PrivilegeDaoImpl extends GenericHibernateDaoImpl<Privilege, Serializable> implements PrivilegeDao {
	
	/** Constructor method. */
		public PrivilegeDaoImpl() {
			super(Privilege.class);
		}
	}

