package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.PrivilegedGroup;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.PrivilegedGroupDao;

/**
 * DAO for table: PrivilegedGroup.
 * @author autogenerated
 */
@Repository
public class PrivilegedGroupDaoImpl extends GenericHibernateDaoImpl<PrivilegedGroup, Serializable> implements PrivilegedGroupDao {
	
	/** Constructor method. */
		public PrivilegedGroupDaoImpl() {
			super(PrivilegedGroup.class);
		}
	}

