package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.ProductPlan;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.ProductPlanDao;

/**
 * DAO for table: ProductPlan.
 * @author autogenerated
 */
@Repository
public class ProductPlanDaoImpl extends GenericHibernateDaoImpl<ProductPlan, Serializable> implements ProductPlanDao {
	
	/** Constructor method. */
		public ProductPlanDaoImpl() {
			super(ProductPlan.class);
		}
	}

