package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.Purchase;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.PurchaseDao;

/**
 * DAO for table: Purchase.
 * @author autogenerated
 */
@Repository
public class PurchaseDaoImpl extends GenericHibernateDaoImpl<Purchase, Serializable> implements PurchaseDao {
	
	/** Constructor method. */
		public PurchaseDaoImpl() {
			super(Purchase.class);
		}
	}

