package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.Quota;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.QuotaDao;

/**
 * DAO for table: Quota.
 * @author autogenerated
 */
@Repository
public class QuotaDaoImpl extends GenericHibernateDaoImpl<Quota, Serializable> implements QuotaDao {
	
	/** Constructor method. */
		public QuotaDaoImpl() {
			super(Quota.class);
		}
	}

