package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.Refund;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.RefundDao;

/**
 * DAO for table: Refund.
 * @author autogenerated
 */
@Repository
public class RefundDaoImpl extends GenericHibernateDaoImpl<Refund, Serializable> implements RefundDao {
	
	/** Constructor method. */
		public RefundDaoImpl() {
			super(Refund.class);
		}
	}

