package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.RewardLateFunction;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.RewardLateFunctionDao;

/**
 * DAO for table: RewardLateFunction.
 * @author autogenerated
 */
@Repository
public class RewardLateFunctionDaoImpl extends GenericHibernateDaoImpl<RewardLateFunction, Serializable> implements RewardLateFunctionDao {
	
	/** Constructor method. */
		public RewardLateFunctionDaoImpl() {
			super(RewardLateFunction.class);
		}
	}

