package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.RewardEarlyFunction;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.RewardEarlyFunctionDao;

/**
 * DAO for table: RewardEarlyFunction.
 * @author autogenerated
 */
@Repository
public class RewardEarlyFunctionDaoImpl extends GenericHibernateDaoImpl<RewardEarlyFunction, Serializable> implements RewardEarlyFunctionDao {
	
	/** Constructor method. */
		public RewardEarlyFunctionDaoImpl() {
			super(RewardEarlyFunction.class);
		}
	}

