package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.TransactionItemPK;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.TransactionItemPKDao;

/**
 * DAO for table: TransactionItemPK.
 * @author autogenerated
 */
@Repository
public class TransactionItemPKDaoImpl extends GenericHibernateDaoImpl<TransactionItemPK, Serializable> implements TransactionItemPKDao {
	
	/** Constructor method. */
		public TransactionItemPKDaoImpl() {
			super(TransactionItemPK.class);
		}
	}

