package com.gnoras.maple.dal.model.dao.impl;

import java.io.Serializable;
import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.gnoras.maple.dal.model.User;
import org.springframework.stereotype.Repository;
import com.gnoras.maple.dal.model.dao.UserDao;

/**
 * DAO for table: User.
 * @author autogenerated
 */
@Repository
public class UserDaoImpl extends GenericHibernateDaoImpl<User, Serializable> implements UserDao {
	
	/** Constructor method. */
		public UserDaoImpl() {
			super(User.class);
		}
	}

